### ISSUE TITLE
Bổ sung kiểu gõ Simple Telex

### ISSUE THREAD

**Issue by hoangstark** [tuyenvm/OpenKey#10]
Mình thấy bộ gõ simple telex khá là tiện cho mấy anh em dev vì hay sử dụng chữ w. Nếu có thể bổ sung thì thật là tuyệt.

Cảm ơn bạn vì dự án

**Comment by tuyenvm** [comment]
Sẽ có trong bản sau luôn ^^, hôm nay ngồi nguyên ngày phục vụ các bạn.

**Comment by tuyenvm** [comment]
Cập nhật bản mới 1.0.17 nha bạn, bản mới đã có tính năng này.

**Comment by ngocphamm** [comment]
Cảm ơn @tuyenvm vì ứng dụng nguồn mở này.

Hai bạn cho mình hỏi ngu cái là Telex với Simple Telex khác nhau như thế nào nhỉ? Mình có tìm qua Google mà chưa thấy khác gì lắm 🤔

**Comment by tuyenvm** [comment]
@ngocphamm Simple Telex thì không gõ "[" thành "ơ", "]" thành "ư", "w" thành "ư", phù hợp với developer. Bộ gõ mặc định simple telex vẫn w thành ư được.

**Comment by dinhtuan1991vt** [comment]
@tuyenvm Hiện tại Simple Telex vẫn gõ được "w" thành "ư". Hy vọng bản sau sẽ chặn cái này vì nhiều lúc code khá bất tiện :D

**Comment by tuyenvm** [comment]
Simple Telex đã ok trong bản 1.0.18
