### ISSUE TITLE
Lỗi khi gõ "z" sau khi gõ telex dấu sắc

### ISSUE THREAD

**Issue by reddevilcf17** [tuyenvm/OpenKey#100]
Ví dụ: gõ "á" sau đó xoá, gõ lại "z" thì chữ z sẽ biến thành chữ "a". Tương tự nếu gõ "é", sau đó xoá đi gõ "z" thì chữ hiện ra vẫn là chữ "a"

**Comment by tuyenvm** [comment]
đã fix trong bản 1.5.2 nhé.
