### ISSUE TITLE
Bị đổi icon trên Menu bar khi dùng Cmd + Tab để chuyển qua lại giữa các màn hình ứng dụng

### ISSUE THREAD

**Issue by reddevilcf17** [tuyenvm/OpenKey#101]
Dù đang cài phím tắt chuyển chế độ gõ là Alt + shift, nhưng khi bấm tổ hợp phím Cmd + Tab (tổ hợp phím này dùng để switch màn hình ứng dụng) icon trên menu bar vẫn chuyển qua lại giữa các chế độ gõ tiếng Việt, tiếng Anh

**Comment by tuyenvm** [comment]
Có thể đây là kết quả của tính năng "Chuyển chế độ thông minh"? Icon trên menu bar vẫn chuyển qua lại nhưng khi gõ phím thì nó vẫn quay trở lại chế độ gõ đúng với ứng dụng đó.

**Comment by tuyenvm** [comment]
Đã cải thiện ở bản 1.6.2 rồi nhé, giờ tốt hơn nhiều rồi: https://github.com/tuyenvm/OpenKey/releases/latest
