### ISSUE TITLE
Lỗi tính năng tự động khôi phục khi đổi ứng dụng

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#103]
Mình đang gõ ở 1 ứng dụng chữ: ngôn ngữ (tới đây là ngưng, không gõ thêm dấu hay khoảng cách)
Sau đó nhảy qua 1 ứng khác gõ 24, cách ra thì sẽ xuất hiện chữ nguwx24

**Comment by tuyenvm** [comment]
Bạn chuyển qua ứng dụng khác bằng phím hay bằng chuột nhỉ?

**Comment by reun** [comment]
Mình chuyển bằng cách dùng 3 ngón trên touchpad kéo quá kéo lại (chuyển qua Desktop khác trên Mac).
Khi mình kéo qua thì con trỏ đang nằm đúng chỗ rồi nên gõ tiếp luôn thì bị lỗi đó.

**Comment by tuyenvm** [comment]
À thế thì đúng rồi, do chưa startNewSession khi dùng thao tác đó, mình dùng máy bàn nên bị miss trường hợp này, sẽ fix nhanh trong bản sau, thanks bạn rất nhiều.

**Comment by tuyenvm** [comment]
đã fix ở bản 1.6 rồi nhé.
