### ISSUE TITLE
Tính năng loại trừ ứng dụng

### ISSUE THREAD

**Issue by levinhtin** [tuyenvm/OpenKey#104]
Cần tính năng cho phép loại trừ những ứng dụng được chọn, tham khảo EVKey.

**Comment by tuyenvm** [comment]
Mình thấy tự động ghi nhớ hay hơn chứ bạn? đỡ phải chọn tay?

**Comment by mrnvdong** [comment]
> Cần tính năng cho phép loại trừ những ứng dụng được chọn, tham khảo EVKey.

nó là tình năng chuyển chế độ thông minh nhé bạn .. Ví dụ bạn dùng Chrome gõ tiếng việt - sang dùng viber để tiếng anh . Thì khi bạn chuyển sang chrome Openkey sẽ tự động chuyển V - sang viber tự động chuyển E. Nhé

**Comment by netherstar** [comment]
@tuyenvm 
Bạn nên làm như bộ gõ mặc định của windows đó là chuyển qua ứng dụng khác cái thì icon sẽ chuyển theo luôn để người dùng dễ nhận biết.
Hiện tại thì chỉ khi gõ phím mới biết. Mình đã biết là Open Key có chế độ này rồi mà còn phải mò mãi mới ra , trách chi nhiều người không biết.

**Comment by tuyenvm** [comment]
@netherstar ok bạn

**Comment by tuyenvm** [comment]
Hiện tại bản macOS và Windows 1.6.2 đều có chuyển chế độ/ loại trừ ứng dụng thông minh tức thì rồi nhé
