### ISSUE TITLE
Lỗi không mở được file trên macOS "no mountable file system"

### ISSUE THREAD

**Issue by thuyld** [tuyenvm/OpenKey#105]
Mình có tải về bản openkey 1.5.2 trên macOS, nhưng khi mở file DMG ra thì bị lỗi này. Admin check giúp lỗi này xem sao :)

**Comment by tuyenvm** [comment]
để mình đính kèm file `zip` trong phần release, cũng nhiều bạn bị như vầy mà mình cũng không hiểu vì sao. Thanks bạn.

**Comment by tuyenvm** [comment]
Bạn tải tại đây nhé https://github.com/tuyenvm/OpenKey/releases/download/1.5.2/OpenKey1.5.2_macOS.zip
