### ISSUE TITLE
Chức năng gõ tắt không hoạt động như ý

### ISSUE THREAD

**Issue by voquanghoa** [tuyenvm/OpenKey#106]
Ví dụ mình tạo gõ tắt `ko` thành `không`thì được. Nhưng nếu mình gõ hoa `Ko`, `KO` thì không có hoạt động.

Mình nghĩ nếu đã định nghĩa gõ tắt `ko` thành `không` thì nên:

Ko thành `Không`
KO thành `KHÔNG`

À nhân tiện, nên cho phép gõ tiếng Việt sau dấu `

Thanks.

**Comment by tuyenvm** [comment]
Thanks bạn, mình sẽ update trong bản sau.

**Comment by tuyenvm** [comment]
Đã update vụ KO thành KHÔNG nhé. https://github.com/tuyenvm/OpenKey/releases/latest
quên vụ dấu ` rồi, mình sẽ update trong bản sau nhé :D
