### ISSUE TITLE
Check phiên bản mới từ cửa sổ giới thiệu làm treo OpenKey

### ISSUE THREAD

**Issue by wolverinevn** [tuyenvm/OpenKey#108]
Mac: 10.13.6
Openkey: 1.5.2 (build 35)

Khi mở cửa sổ Giới thiệu rồi bấm vào Kiểm tra phiên bản mới và có phiên bản mới thì cả hai cửa sổ thông báo đều bị treo.

![Screen Shot 2019-09-26 at 9 50 22 AM](https://user-images.githubusercontent.com/30788067/65654567-7f9df600-e043-11e9-94ad-7e51b565f738.png)

**Comment by tuyenvm** [comment]
@wolverinevn bạn update bản mới 2.0.1 xem còn treo không nhé.
