### ISSUE TITLE
Cải tiến chức năng cập nhật phiên bản mới

### ISSUE THREAD

**Issue by voquanghoa** [tuyenvm/OpenKey#109]
Mình bấm nút Kiểm tra phiên bản mới rồi mặc định bấm vào nút xanh

![image](https://user-images.githubusercontent.com/10450325/65814349-ace8d080-e20a-11e9-95f9-365b0ad58bda.png)

Mấy lần mà không thấy phản ứng gì. Tưởng lỗi, ai dè cái nút mặc định màu xanh lại là `Không`, mình nghĩ nên đổi lại. Primary Button phải là `Có`.

Hoặc giả nên có chức năng tự động kiểm tra cập nhật lúc khởi động hoặc tự động kiểm tra khởi cập nhật hàng ngày.

Nhân tiện

- Cái donate nên có thêm mấy nguồn nữa thì chắc mọi người dễ donate hơn thay vì chỉ có Paypal

- Cái gõ tắt không hoạt động tốt với tự động gõ chữ hoa đầu câu. Tức là nếu từ đầu câu được gõ tắt thì nó sẽ viết thường.

**Comment by tuyenvm** [comment]
OK mình sẽ đổi lại nút.
Hiện vẫn có kiểm tra cập nhật lúc khởi chạy OpenKey đó bạn.
Donate thêm  momo ổn không bạn?
Ý cuối bạn ví dụ trường hợp cụ thể được không?

**Comment by voquanghoa** [comment]
Momo là ok đó bạn vì Momo khá phổ biến, cũng tiện lợi mà lại không tốn phí.
Cái cuối. Ví dụ mình đặt viết tắt ko thành `không`, bt thành bình thường thì

![image](https://user-images.githubusercontent.com/10450325/65814494-cee35280-e20c-11e9-9b12-59c72c241ab0.png)

Con trỏ chuột đang đứng ngay sau chữ Bt (chữ B viết hoa tự động) --> Nếu mình nhấn space thì nó thành

![image](https://user-images.githubusercontent.com/10450325/65814517-00f4b480-e20d-11e9-99a3-f0ca544e4dbb.png)

Chữ B đã từ uppercase thành lowercase ngay

**Comment by tuyenvm** [comment]
À mình hiểu rồi, nó không tự động ghi hoa khi dùng với tính năng "Viết Hoa chữ cái đầu câu"
Rất cảm ơn bạn 👍

**Comment by tuyenvm** [comment]
Mình đã cập nhật ở bản build mới nhất rồi nha bạn, vẫn version 1.6.2, nhưng là build 40 rồi.
