### ISSUE TITLE
Khôi phục phím với từ sai

### ISSUE THREAD

**Issue by ga4so9** [tuyenvm/OpenKey#11]
Mình thấy tính năng này nhiều bộ gõ tiếng việt đang dùng, và cũng nhiều người cần trong đó có  mình, vì nhiều khi mình gõ tiếng anh nhưng không chuyển bộ gõ từ tiếng Việt sang tiếng Anh.
Bạn add thêm nhé.
Mình đang xài 10.14.5 thì thấy chạy ngon lành!
Thank bạn nhiều :D

**Comment by causelove94** [comment]
Mình cũng rất cần tính năng này ạ. Ví dụ như khi gõ từ "ưindows" thấy sai chính tả sẽ tự khôi phục về từ "windows" ấy. Bạn bổ sung thêm tính năng này nhé. Bạn tác giả rất nhiệt tình và thân thiện, mình sẽ ủng hộ bạn, cảm ơn bạn nhiều!

**Comment by orekasep** [comment]
Đúng là một tính năng cần có. Vote +1

**Comment by tuyenvm** [comment]
mình sẽ thêm tính năng này vào bản tiếp theo nhé, nhiều bạn request quá nên miss mất tính năng này.

**Comment by khanhvu14** [comment]
quá ngon, mong chờ quá
