### ISSUE TITLE
Tính năng kiểm tra chính tả trên Windows

### ISSUE THREAD

**Issue by kurokeita** [tuyenvm/OpenKey#110]
Kiểm tra chính tả tự động reset trạng thái về bật sau mỗi lần mở openkey. Nếu mình tắt kiểm tra chính tả rồi thì mỗi lần tắt openkey và mở lại, nó lại tự bật, tương tự với restart máy.

**Comment by tuyenvm** [comment]
Bản mac hay Windows vậy bạn

**Comment by kurokeita** [comment]
à quên mất, mình dùng windows nhé bạn

**Comment by tuyenvm** [comment]
Mình fix ở bản build mới rồi nhé, nếu bạn đang dùng OpenKey 1.6.2 cho Windows thì bạn có thể dùng tính năng update tự động để cập nhật.

**Comment by kurokeita** [comment]
Thanks bạn nhé, bản mới hoạt động tốt rồi
