### ISSUE TITLE
tắt thông báo cập nhật.

### ISSUE THREAD

**Issue by hungminhtran** [tuyenvm/OpenKey#115]
Thật mình thấy phiền lắm, mỗi lần mở lên là hỏi cập nhật. Mình Mong muốn có tuỳ chọn để tắt tính năng này đi.

**Comment by tuyenvm** [comment]
Sẽ có tùy chọn trong bản sau :D, chứ bị phàn nàn về auto update nhiều rồi.

**Comment by netherstar** [comment]
@tuyenvm 
Mình đang dùng bản 1.6.2 (hình như là bản mới nhất rồi) nhưng mỗi lần mở lên vẫn bị hỏi là có bản mới, có muốn cập nhật không? Ấn vào "có" thì hiện lỗi.

**Comment by tuyenvm** [comment]
@netherstar Bạn tạm tải lại bản Windows trên github nhé, đó là bản build mới nhưng mình không thay đổi số hiệu phiên bản (vẫn 1.6.2)
Còn OpenKeyUpdate để mình xem lại.

**Comment by tuyenvm** [comment]
@netherstar 
OpenKeyUpdate mình build dùng shared dll nên bị lỗi runtime, T_T, mình sẽ cập nhật lại bản Windows, bạn khoan update nhé

**Comment by tuyenvm** [comment]
@netherstar xong rồi, bạn tải lại thủ công ở [đây](https://github.com/tuyenvm/OpenKey/releases/download/1.6.2/OpenKey1.6.2-Windows.zip) nha

**Comment by netherstar** [comment]
@tuyenvm 
Có lẽ trên web open-key chỉ nên up bản stable, có thể up riêng bản dev, bản test lên chỗ khác cho anh em nào thích, muốn test.

**Comment by tuyenvm** [comment]
OK mình sẽ rút kinh nghiệm, sẽ có kênh cho dev, khi nào ổn đỉnh sẽ chuyển qua production, thanks @netherstar

**Comment by netherstar** [comment]
@tuyenvm Bản mới nhất bạn mới up bị lỗi thoát lúc nào không biết, mở lại thì không chạy.

**Comment by tuyenvm** [comment]
> @tuyenvm Bản mới nhất bạn mới up bị lỗi thoát lúc nào không biết, mở lại thì không chạy.

Hiện giờ còn bị không bạn?

**Comment by tuyenvm** [comment]
@hungminhtran có bản cập nhật [1.6.5](https://github.com/tuyenvm/OpenKey/releases/tag/1.6.5) cho phép tắt kiểm tra cập nhật rồi nha bạn, tắt ở trong phần "Giới thiệu"

**Comment by hungminhtran** [comment]
Cảm ơn bạn 👍
