### ISSUE TITLE
Xung đột với Adobe Photoshop và Illustrator

### ISSUE THREAD

**Issue by saosangmo** [tuyenvm/OpenKey#117]
Khi mình cài đặt và khởi động lại máy xong thì cả 2 phần mềm của Adobe Photoshop CC 2018 bị lỗi là chỉ hiển thị hand tool và không làm được gì trên 2 phần mềm này.

Đành phải quay về dùng tạm soft khác đợi các bạn fix lỗi này.

Cảm ơn về phần mềm tuyệt vời của các bạn!

**Comment by tuyenvm** [comment]
Mình mới tìm hiểu thì tạm thời nếu stuck Photoshop ở hand tool thì bấm spacebar vài lần thì nó hết.

**Comment by tuyenvm** [comment]
À bạn sử dụng bản Windows hả.
Bạn thử bật bàn phím ảo lên, bấm vào spacebar nhiều lần là hết.
Và có vẻ như do gõ tắt thật.

**Comment by hakuscent** [comment]
Mình cũng đang gặp tình trạng này, mong sẽ có bản fix sớm

**Comment by tuyenvm** [comment]
Hi @hakuscent @saosangmo có bản cập nhật [1.6.5](https://github.com/tuyenvm/OpenKey/releases/tag/1.6.5) fix lỗi này rồi nha các bạn.
