### ISSUE TITLE
[Feature] Thêm tính năng cho tuỳ chọn bật/tắt bộ gõ 

### ISSUE THREAD

**Issue by thuyld** [tuyenvm/OpenKey#118]
Dear admin,
Mình hi vọng bộ gõ OpenKey này nếu được bạn thêm được tính năng cho tuỳ chọn ignore bộ gõ này trong 1 số phần mềm cụ thể được không? ví dụ như khi code, mình xài tiếng việt hơi bất tiện. 
Cám ơn tác giả về phần mềm gõ tuyệt vời :)

**Comment by tuyenvm** [comment]
Bạn dùng thử tính năng “chuyển chế độ thông minh” đi, mình có mô tả ở trang chủ đó

**Comment by tuyenvm** [comment]
@thuyld bạn dùng thử rồi cho mình biết nhé, vì ít người biết đến tính năng này quá nên mình đang cân nhắc cho thêm tính năng chọn loại trừ ứng dụng bằng tay vô

**Comment by netherstar** [comment]
> @thuyld bạn dùng thử rồi cho mình biết nhé, vì ít người biết đến tính năng này quá nên mình đang cân nhắc cho thêm tính năng chọn loại trừ ứng dụng bằng tay vô

Có tooltip như phiên bản 2.0 này thì chắc nhiều người sẽ để ý, biết hơn. Theo mình không nên cho config cứng vào, loạn và rối.

**Comment by thuyld** [comment]
> @thuyld bạn dùng thử rồi cho mình biết nhé, vì ít người biết đến tính năng này quá nên mình đang cân nhắc cho thêm tính năng chọn loại trừ ứng dụng bằng tay vô

Ok, mình thấy auto change ngôn ngữ như này khá ngon. Vẫn đang xài tốt. Thanks bạn

**Comment by tuyenvm** [comment]
Vậy không cần tự thêm bằng tay nữa he, tự động như hiện tại làm quá tốt rồi.
