### ISSUE TITLE
Không tự khôi phục với từ nẽt

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#119]
Khi gõ Next thì ra nẽt, bấm cách ra cũng không tự khôi phục.

**Comment by tuyenvm** [comment]
mình sẽ chỉ cho dấu sắc trong các từ có phụ âm cuối ch, t trong bản sau.

**Comment by reun** [comment]
Mình nghĩ là thêm dấu nặng nữa, vẫn có những từ như:
tạch
chịch

**Comment by tuyenvm** [comment]
Ok bạn

**Comment by tuyenvm** [comment]
Đã cải thiện ở bản 2.0.2 ^^
