### ISSUE TITLE
Lỗi khi gõ 'bar' unicode tổ hợp, bỏ dấu tự do

### ISSUE THREAD

**Issue by luatvudinh** [tuyenvm/OpenKey#12]
Lỗi khi gõ 'bar' chuyển thành 'ar' ở chế độ gõ tự do với unicode tổ hợp.
![Screen Shot 2019-07-30 at 12 02 23 PM](https://user-images.githubusercontent.com/22373743/62102153-1f4c3b80-b2c2-11e9-9393-5e05a86d177f.png)
[Screen Recording 2019-07-30 at 12.02.49 PM.zip](https://github.com/tuyenvm/OpenKey/files/3445259/Screen.Recording.2019-07-30.at.12.02.49.PM.zip)

**Comment by tuyenvm** [comment]
đã fix trong bản [1.0.19](https://github.com/tuyenvm/OpenKey/releases)
