### ISSUE TITLE
Phím nóng để tắt tiếng Việt

### ISSUE THREAD

**Issue by voquanghoa** [tuyenvm/OpenKey#120]
Hi bạn

Bên Unikey có tính năng tạm ngưng gõ tiếng Việt với từ hiện tại

![image](https://user-images.githubusercontent.com/10450325/66304798-3776b180-e928-11e9-97ad-c496338d2cb5.png)

https://www.unikey.org/support/ukmanual.html

Cái này có ích khi mình gõ 1 câu tiếng Việt dài và có xen lẫn vài từ tiếng anh.

Hoặc mình cố tình gõ 1 từ có dấu nhưng không có trong từ điển tiếng Việt.

Khi đó nếu mình gõ

`or` --> Ra `ỏ`
Còn nếu gõ `o` `ctrl` `r` --> or (kể cả khi đang bật tiếng Việt)

Bên mac thì nên thay `ctrl` bởi `cmd`

Bạn tham khảo nha.

**Comment by tuyenvm** [comment]
ok bạn, mình sẽ tích hợp vào trong bản kế tiếp

**Comment by netherstar** [comment]
Phiên bản 2.0 hiện tại mình gõ `o` `pause` `r` cũng ra or rồi mà?

**Comment by tuyenvm** [comment]
@netherstar có thể phím đó chỉ break từ thôi, ví dụ gõ `o` `pause` `r` `e` `e` nó vẫn ra `orê`, thay vì phải ra `oree` mới đúng.

**Comment by tuyenvm** [comment]
đã thêm tính năng này ở bản 2.0.1 (macOS) nhé.
<img width="672" alt="openkey-main-control" src="https://user-images.githubusercontent.com/7700801/66904149-cf158780-f02d-11e9-86b0-5ff8a1c25beb.png">

**Comment by voquanghoa** [comment]
Tuyệt vời, mình đã cập nhật lên và thấy ok 💯💯💯
