### ISSUE TITLE
Lỗi trên Google Slides (macOS Catalina)

### ISSUE THREAD

**Issue by nguyenhuuhanhch** [tuyenvm/OpenKey#123]
1. Khi không bật gửi từng phím thì lỗi khi gõ trong Google Slides
2. Ví dụ như 
Kế hoạch tuyển dụng
-> kế ho tu dụg
3. Bật gửi từng phím thì ok nhưng có thể đây là lỗi đúng không?

**Comment by tuyenvm** [comment]
Đó là 2 kiểu gửi dữ liệu khác nhau. Giờ bạn để chế độ gửi từng phím dùng xuyên suốt cũng được, nhưng nó lại bị lỗi khi dùng OpenOffice trong khi chế độ không gửi từng phím lại chạy tốt.
Vậy nên nó không phải là lỗi, tuỳ vô từng phần mềm mà mình chỉnh chế độ gõ thích hợp.

**Comment by nguyenhuuhanhch** [comment]
Gửi từng phím nó có ảnh hưởng tốc độ gõ không bạn? 
Cơ bản khác như thế nào nhỉ sharing thêm 1 tí nếu có sẵn docs rồi

**Comment by tuyenvm** [comment]
Về lý thuyết thì gửi từng phím sẽ chậm hơn, nhưng không đáng kể đâu bạn.
Ví dụ gõ từ "phương" bằng cách gõ "p h u o n g w" thì mặc định sẽ gửi chuỗi "ương", còn gửi gửi từng phím thì sẽ gửi lần lượt "ư ơ n g"
