### ISSUE TITLE
Loại bỏ thông báo ứng dụng đang hoạt động!

### ISSUE THREAD

**Issue by dungmv** [tuyenvm/OpenKey#124]
Thông báo "Ứng dụng đang hoạt động" trông không hay lắm, chỉ nên thông báo khi có bất thường, còn khi đang bình thường không nên có thông báo. như thế nhìn bảng điều khiển sẽ gọn và sạch hơn

**Comment by tuyenvm** [comment]
OK : )), đó là tàn tích từ những phiên bản đầu tiên :D

**Comment by tuyenvm** [comment]
Đã loại bỏ ở bản 2.0.2.
