### ISSUE TITLE
Cải tiến việc bỏ dấu

### ISSUE THREAD

**Issue by nhaancs** [tuyenvm/OpenKey#128]
Trong chế độ telex, khi gõ "G" "o" "o" "g" "l" "e" và ấn dấu cách ra thì kết quả nên là "Google " thay vì "Gôgle "

**Comment by voquanghoa** [comment]
Mình dùng trên Mac và khi gõ `G` `o` `o` `g` `l` `e` thì nó ra `Gôgle` nhưng nếu mình gõ tiếp `space` thì nó lại ra `Google`. Nói chung là đúng như mong đợi và không bị như trên.

**Comment by tuyenvm** [comment]
@nhaancs Bật kiểm tra chính tả và dùng tính năng "Phục hồi phím với từ sai" đi e.

**Comment by nhaancs** [comment]
Thanks c @tuyenvm
