### ISSUE TITLE
Tính năng gõ tắt

### ISSUE THREAD

**Issue by hoangnamitc** [tuyenvm/OpenKey#13]
Chào tác giả,

Hiện tôi chưa thấy tính năng gõ tắt trên ứng dụng. Hy vọng tác giả có thể bổ sung tính năng này trong phiên bản tiếp theo.

Xin cảm ơn!

**Comment by tuyenvm** [comment]
Tính năng này làm khá tốn thời gian, nên mình sẽ thêm vào trong phiên bản sau nữa (1.1.0).
Cảm ơn bạn đã sử dụng chương trình

**Comment by tuyenvm** [comment]
Gõ tắt đã có trong bản 1.1 mới rồi nha bạn.

**Comment by hoangnamitc** [comment]
Mình đã thử quá và hoạt động rất tốt. cảm ơn ad.
Có một thắc mắc là nội dung gõ tắt mình nhập vào có sao lưu được ko? Nội dung gõ tắt đó có được bảo lưu trong các phiên bản tiếp theo không?

**Comment by tuyenvm** [comment]
Những từ gõ tắt được lưu trong Preference giống như các cấu hình khác:
Cụ thể là trong: /Users/[User]/Library/Preferences/com.tuyenmai.openkey.plist
Nên có update bản mới thì dữ liệu sẽ không bị mất bạn nhé.

**Comment by hoangnamitc** [comment]
Vậy thì tuyệt vời rồi. cảm ơn ad.
