### ISSUE TITLE
Tắt tính năng kêu beep trên Windows nhưng mở lại vẫn kêu

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#130]
Trên Windows mình tắt chức năng kêu beep, xong thoát ứng dụng. Sau đó mở lại ứng dụng thì tiếng kêu vẫn còn khi mình ấn phím Alt + Z.
Lỗi này khi mà mình bật "hiển thị bảng này khi khởi động" lên.

**Comment by tuyenvm** [comment]
À, Hệ Windows thì Alt + phím nào nó cũng tự kêu beep mà nhỉ?

**Comment by tuyenvm** [comment]
Đã check, bấm phím alt + 1 phím tắt không có trên thanh menu nó sẽ kêu beep.
VD: Notepad: Alt + F -> mở menu file -> không kêu.
Alt + Z -> kêu vì không có menu với phím tắt Z.
