### ISSUE TITLE
Nên tối ưu tính năng chuyển đổi nhanh tiếng Anh - tiếng Việt

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#131]
Khi chuyển nhanh ứng dụng tiếng Anh, tiếng Việt bằng cách giữ phím Alt + z + z ... + z (giữ phím Alt và bấm nhiều lần phím z). Mỗi lần ấn phím z thì sẽ chuyển ngôn ngữ.

**Comment by tuyenvm** [comment]
Đã cải thiện ở bản 2.0.2, thanks ^^
