### ISSUE TITLE
Chức năng tắt nhanh bộ gõ tiếng Việt không tương thích với phím tắt bật tắt tiếng Việt

### ISSUE THREAD

**Issue by voquanghoa** [tuyenvm/OpenKey#132]
Thỉnh thoảng mình không gõ được tiếng Việt sau khi bật từ E qua V, check một hồi thì mới phát hiện ra nguyên nhân như thế này:

Mình đang để phím tắt để bật tắt gõ tiếng Việt là Shift + Cmd:

![image](https://user-images.githubusercontent.com/10450325/67561732-95d4ca00-f747-11e9-8086-5b22f1c52f44.png)

Như vậy, khi mình muốn bật chế độ gõ tiếng Việt thì mình sẽ bấm Shift + Cmd.

Tuy nhiên, khi mình bấm Cmd thì bộ gõ cho rằng mình đang muốn tắt nhanh bộ gõ.

Kết quả: sau khi bật E qua V, từ đầu tiên sẽ không gõ tiếng Việt được.

Mình nghĩ giải pháp là khi đang chế độ E thì chức năng `Tạm tắt OpenKey...` cũng bị vô hiệu hoá luôn.

**Comment by tuyenvm** [comment]
Đã cải thiện ở bản 2.0.2 ^^
