### ISSUE TITLE
Lỗi gõ Ê và Đ

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#135]
Gõ `shift` + `e` + `e` thì ra E Ê và `shift` + `d` + `d` (giữ phím shift) thì ra D Đ
Bỏ `check sửa lỗi gợi ý trình duyệt Excel` thì ra EÊ và DĐ
Bạn nên viết thêm phần unit test.

**Comment by tuyenvm** [comment]
Nếu dùng các trình duyệt Chromium thì vài tab hệ thống bật tính năng “sửa lỗi Chromium” nhé bạn

**Comment by thanhngch** [comment]
Mình test trên Windows 10 và sử dụng Notepad để test

**Comment by tuyenvm** [comment]
Còn case này thì tắt gtv đi còn bị không bạn?

**Comment by thanhngch** [comment]
lỗi do gotiengviet, nên close issue luôn
