### ISSUE TITLE
Lỗi gõ chữ in hoa với phím Shift

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#136]
Giữ phím `shift` rỗi gõ từ `thường` hoặc từ `lỗi` thì sẽ ra `THUOƯƠNGƯỜNG` và `LOÔIỖI`
Hoặc bật Capslock rồi giữ phím shift thì ra lỗi tương tự (với in thường)

**Comment by tuyenvm** [comment]
Không biết bạn có đang dùng chung với bộ gõ nào khác, hoặc chương trình can thiệp bàn phím nào khác không nhỉ 😅

**Comment by thanhngch** [comment]
do mình bật bộ gõ https://www.trankynam.com/gotv/ để chế độ tiếng anh nó bị lỗi vậy :D

**Comment by tuyenvm** [comment]
Thử tắt đi xem có lỗi không, mình chắc chắn là không có lỗi này 😄, chứ 2 chương trình hook bàn phím cùng lúc thì khó sửa lắm, mặc dù gtv bật chế độ tiếng Anh, nhưng nó vẫn hook bàn phím.

**Comment by thanhngch** [comment]
tắt đi hết bị rồi, bạn đóng issue lại luôn
