### ISSUE TITLE
Lỗi không gõ được tiếng Việt ngay với khi chuyển ngôn ngữ bằng Alt + z

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#138]
Đang chế độ tiếng anh, bấm `Alt` + `z` thì hiện tiếng Việt nhưng không gõ ngay được bằng tiếng Việt. 
Test trên Windows 10.

**Comment by tuyenvm** [comment]
Bị dính “tạm tắt OpenKey bằng phím Alt”, tắt đi sẽ bình thường

**Comment by thanhngch** [comment]
> Bị dính “tạm tắt OpenKey bằng phím Alt”, tắt đi sẽ bình thường

Mình cũng test thấy tắt chức năng này đi thì hết lỗi.
