### ISSUE TITLE
Gõ tiếng việt bị lỗi trên textwrangler

### ISSUE THREAD

**Issue by tony-dtn** [tuyenvm/OpenKey#14]
Khi gõ tiếng việt ở chế độ telex trên text wrangler thì bị lỗi, ký tự bị tự xoá

**Comment by tuyenvm** [comment]
Sẽ hỗ trợ trong phiên bản 1.0.17

**Comment by tuyenvm** [comment]
Cập nhật bản mới 1.0.17 nha bạn, bản mới đã có tính năng này.

**Comment by tony-dtn** [comment]
Mình đã cài bản 1.0.17 và hoạt động tốt với textwrangler. Cảm ơn bạn.
