### ISSUE TITLE
[Win] Gõ tiếng Việt có bị lỗi khi chuyển giữa hai chương trình bằng Alt + tab trên Windows

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#140]
Mô tả: chọn chế độ gõ tiếng việt, bật 'Tạm tắt Openkey bằng phím alt'. Bật Notepad, tiếp tục mở cửa sổ Notepad mới (File -> new Windows). Gõ một từ tiếng việt ví dụ `công` rồi ấn `Alt` + `tab` để chuyển sang Nodepad kia. Gõ tiếp `j` thì bị lỗi.

Khi tắt 'Tạm tắt Openkey bằng phím alt' thì vẫn bị lỗi là không thể gõ được tiếng việt ở cả 2 chương trình Nodepad.

**Comment by tuyenvm** [comment]
Đã cải thiện ở bản 2.0.2 ^^
