### ISSUE TITLE
[Win] Chức năng gõ tắt chưa đúng

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#142]
Thêm một từ gõ tắt: `tv` -> `Tiếng Việt`
Gõ `học tv:` ra `học TIếNG VIệT:`  và `Học tv?` ra `Học TIếNG VIệT?`

Ngoài ra nên thêm thêm phím `tab` để gõ nhanh thay cho dấu câu (khi người ta không muốn gõ tắt mà không muốn thêm dấu câu ở cuối).

Thêm nữa là có thêm chức năng bỏ gõ nhanh ví dụ vừa muốn gõ `tv` và `Tiếng Việt` trong một câu. Nên dùng phím `Ctrl` ở cuối để bỏ gõ nhanh.

**Comment by tuyenvm** [comment]
Đã cải thiện ý 1.

Mình thấy phím `tab` để gõ tắt, thì cũng để lại 1 ký tự tab (con trỏ nhảy qua bên phải 1 khoảng xa), cũng phải xóa ký tự tab. Hiện tại có thể kích hoạt gõ tắt bằng các dấu ngắt câu, phím space và enter.

Nếu không muốn kích hoạt gõ tắt thì có thể dùng phím mũi tên, ví dụ gõ `ko`, `mũi tên phải`. Phím Ctrl đã trùng với một tính năng khác rồi.

**Comment by thanhngch** [comment]
Phím mũi tên ở hơi xa nhưng có còn hơn không ^^

**Comment by thanhngch** [comment]
Bản 2.0.2 cũng khá ổn rồi, còn phím mũi tên khi gõ trên excel lại bị nhảy sang ô khác. Nhưng cũng không sao.

**Comment by thanhngch** [comment]
Bạn xem lại 2 issue [134](https://github.com/tuyenvm/OpenKey/issues/134) với [139](https://github.com/tuyenvm/OpenKey/issues/139) luôn nha

**Comment by tuyenvm** [comment]
OK bạn
