### ISSUE TITLE
[Win] Bị lỗi với phím End và Home

### ISSUE THREAD

**Issue by thanhngch** [tuyenvm/OpenKey#143]
Gõ `hoạt đ` -> `Home` (phím home hoặc phím mũi tên sang trái) -> `End` (phím end hoặc phím mũi tên sang phải) -> gõ tiếp `ộng` mà không được.

Lỗi này bị khi bật tính năng kiểm tra chính tả.

**Comment by thanhngch** [comment]
Với phím `Insert` và `Delete` cũng bị lỗi tương tự là không gõ được tiếng Việt với mấy phím này.

**Comment by tuyenvm** [comment]
Đã cải thiện ở bản 2.0.2 ^^
