### ISSUE TITLE
Có thể thêm phím tắt cho phím chuyển được không

### ISSUE THREAD

**Issue by huyparody** [tuyenvm/OpenKey#15]
Hi anh, em rất hài lòng về chất lượng app, nhưng phiền anh có thể thêm 1 tuỳ chọn bind phím tắt control + space để chuyển phím dc ko ạ?

**Comment by tuyenvm** [comment]
sẽ có trong bản sau bạn nhé

**Comment by n13minh** [comment]
Cám ơn Tuyên đã đóng góp 1 bộ gõ tiếng Việt tốt cho cộng đồng macOS user Việt Nam. Mình bắt đầu sử dụng sau khi đọc bài viết trên Tinh Tế sáng nay, phải nói rất hài lòng với bộ gõ. 1 điều mình khá vui là vô tình phím tắt chuyển ngôn ngữ lại trùng với thiết lập mà mình hay sử dụng (Option + Z) :).

**Comment by huyparody** [comment]
> sẽ có trong bản sau bạn nhé

cám ơn anh nhiều ạ :D

**Comment by tuyenvm** [comment]
@n13minh Vì mình cũng đang dùng tổ hợp phím Option + Z mà ^^. Nhưng trong bản sau sẽ cho người dùng tuỳ chọn phím chuyển phục vụ nhiều người hơn. Cảm ơn bạn đã ủng hộ ứng dụng.

**Comment by tuyenvm** [comment]
Cập nhật bản mới 1.0.17 nha bạn, bản mới đã có tính năng này.

**Comment by orekasep** [comment]
Một bộ gõ tuyệt vời. Cảm ơn Tuyển nhiều vì đã có đóng góp cho cộng đồng người sử dụng Mac.

**Comment by n13minh** [comment]
@tuyenvm: phiên bản mới (1.0.17 tốt quá, cám ơn bạn tác giả rất nhiệt tình.
