### ISSUE TITLE
Lỗi gõ phím d

### ISSUE THREAD

**Issue by theblackturtle** [tuyenvm/OpenKey#151]
Khi gõ `d` thì OpenKey tự động xoá 1 phím phía trước và chuyển thành chữ `đ`
Ex: `Không ` -> `Khôngđ` hoặc `Không` -> `Khônđ`
Nhưng khi viết hoa chữ D thì vẫn bình thường

Os: 10.15.1
OpenKey version: 2.0.3

**Comment by tuyenvm** [comment]
Lỗi lạ quá? @theblackturtle  có đang bật bộ gõ nào khác không?

**Comment by theblackturtle** [comment]
Không bác. Mấy hôm trước gõ vẫn bình thường mà

**Comment by theblackturtle** [comment]
Nếu gõ phím `d` ở đầu câu thì tự chuyển thành chữ `đ`

**Comment by theblackturtle** [comment]
Mình đã fix được. Do trong Mac, khi chỉnh `Key Repeat` cao quá là bị như thế. Giảm nó xuống là hết bị :D
