### ISSUE TITLE
Không gõ được tiếng Việt trên VSCode khi chọn Language Mode là Markdown và cài extension Markdown All in One

### ISSUE THREAD

**Issue by hellovietduc** [tuyenvm/OpenKey#152]
**OS:** MacOS Catalina 10.15.1
**VSCode:** v1.40.2
**Markdown All in One extension:** v2.5.1
**OpenKey:** v2.0.3 build 47

**Cách tái hiện:** Mở VSCode, bật extension Markdown All in One, chọn Language Mode (syntax highlighting) là Markdown, gõ tiếng Việt -> chữ tiếng Việt có dấu có xuất hiện một tích tắc trước khi bị nháy và thay bằng chữ tiếng Việt không dấu.

Mặc dù biết là conflict với extension của VSCode, nhưng vẫn muốn báo cho bác xem có thể fix được không. Thanks! 😃

**Comment by tuyenvm** [comment]
để em tìm cách 😁

**Comment by t2hv33** [comment]
Lỗi này có ai biết cách fix chưa ạ

**Comment by mwolfinspace** [comment]
Vẫn đang hóng lỗi này được fix.

**Comment by t2hv33** [comment]
@hellovietduc @mwolfinspace 
Bug này là do cái key `onBackspaceKey` keybinding
Vào VSCode xóa hotkey này trong Markdown All In One là gõ tiếng Việt bình thường nha mọi người.
Chi tiết xem link dưới đây.
https://github.com/yzhang-gh/vscode-markdown/issues/617#issuecomment-585629661

**Comment by hellovietduc** [comment]
Hay quá, cảm ơn bạn nha @t2hv33

**Comment by coibaka** [comment]
> @hellovietduc @mwolfinspace Bug này là do cái key `onBackspaceKey` keybinding Vào VSCode xóa hotkey này trong Markdown All In One là gõ tiếng Việt bình thường nha mọi người. Chi tiết xem link dưới đây. [yzhang-gh/vscode-markdown#617 (comment)](https://github.com/yzhang-gh/vscode-markdown/issues/617#issuecomment-585629661)

Em cảm ơn ạ, tìm hoài giờ mới thấy

**Comment by ooker777** [comment]
có bạn nào đọc lỗi bên đó rồi có thể tóm tắt lại vấn đề là gì được không?

**Comment by coibaka** [comment]
Mình nhớ không nhầm thì do việc shortcut key của markdown trùng với phím gõ
tiếng Việt, mấy dấu mũ hay chữ, nên là vào xoá mấy shortcut key đó đi là
viết được à, ☺️

Vào 18:01, Th 5, 11 thg 7, 2024 Ooker ***@***.***> đã viết:
