### ISSUE TITLE
Khong cai dat duoc open-key tren mac os el capitan

### ISSUE THREAD

**Issue by linhndd** [tuyenvm/OpenKey#153]
Toi khong the cai duoc openkey tren mac os el capitan 10.11. Bao loi nhu ben duoi 
https://prnt.sc/q44jxt

Co the chi toi cach cai dat khac khong?

**Comment by tuyenvm** [comment]
Bạn vào phần release download file zip thay vì dmg nhé

**Comment by linhndd** [comment]
Cảm ơn tác giả, mình đã sử dụng được thành công
