### ISSUE TITLE
Tự động bị chuyển ngôn ngữ khi Command + Tab

### ISSUE THREAD

**Issue by quanKM** [tuyenvm/OpenKey#155]
Minh thường xuyên dùng Command + Tab và nhận thấy mỗi lần dùng là OneKey chuyển ngôn ngữ.

![Screen Shot 2019-12-31 at 15 29 25](https://user-images.githubusercontent.com/38641481/71615160-5c568a00-2be2-11ea-8532-4aa94250c652.png)

Setting key của mình đây

**Comment by tuyenvm** [comment]
Trong tab "Bộ gõ" bạn có dùng tính năng "Chuyển chế độ thông minh" không?
Có thể Command + Tab qua ứng dụng kia, do ứng dụng đó trước đó dùng chế độ tiếng Anh nên OpenKey tự chuyển ngôn ngữ.

**Comment by quanKM** [comment]
@tuyenvm Ok rồi bạn, mình close issue tại đây.
