### ISSUE TITLE
Gõ tiếng việt bị lỗi trên Telegram for macos 5.9.2

### ISSUE THREAD

**Issue by neverbestboy** [tuyenvm/OpenKey#159]
Ký tự đầu tiên nếu là unicode sẽ bị lỗi, Focus bị lùi lại. Ví dụ chữ đ

**Comment by tuyenvm** [comment]
Thử lần lượt tắt/bật thử tính năng "Sửa lỗi gợi ý", "Giử từng phím" xem có khắc phục được không bạn nhé?

**Comment by neverbestboy** [comment]
vẫn không được nhé

**Comment by neverbestboy** [comment]
Telegram update lại, mọi thứ bình thường như cũ rồi nhé :D

**Comment by tuyenvm** [comment]
ok! vậy close issue.
