### ISSUE TITLE
Chữ đầu tiên có dấu bị nhảy chữ ở Telegram Desktop [Mac]

### ISSUE THREAD

**Issue by nguyenrom** [tuyenvm/OpenKey#161]
Các chữ có dấu ở đầu như:
- Ô
- Đ
- v.v.

Khi gõ đều bị nhảy, ví dụ chữ: đúng → úngđ

Chi tiết:
https://www.loom.com/share/ba63ac9d506d492e89c9441137359416

**Comment by tuyenvm** [comment]
Trước có bạn cũng gặp lỗi với Telegram #159 bác thử update telegram xem có bình thường lại không?

**Comment by nguyenrom** [comment]
Mình dùng bản Instagram mới nhất luôn, mình dùng bản Desktop (bị lỗi). Còn ở bản Telegram Lite thì không.

**Comment by tuyenvm** [comment]
Mình mới check lại thì Telegram bản mới nhất trên Mac App Store 5.9.2 bị lỗi.
Mình vào trang chủ Telegram thì thấy có bản 5.9.3 thì hết lỗi.
@nguyenrom update thử.
https://macos.telegram.org

**Comment by nguyenrom** [comment]
Cảm ơn @tuyenvm , bản ở trang chủ của Telegram lại okie.
