### ISSUE TITLE
Bị delay hiển thị chữ khi gõ trên Coda

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#165]
Khi gõ bằng Openkey trên [Coda](https://coda.io/d/Test-coda_d5LSXKUDmf-/Test-coda_sut5w#_lu7I3), thì thấy bị delay rất lâu, 1 lúc sau mới hiện ra các ký tự, cảm giác lag lag khá khó chịu và dễ gõ sai.

Thử tắt đi 1 số setting về kiểm tra chính tả thì thấy có cải thiện 1 chút. Mà so với bộ gõ mặc định của Mac thì vẫn chậm hơn.

Xem video: https://share.getcloudapp.com/wbumwolg

**Comment by reun** [comment]
@tuyenvm nếu được ưu tiên fix giúp mình vấn đề này nhé. 2 lỗi kia mình report trước đó từ từ cũng được. 
Hiện tại mình thao tác trên Coda nhiều mà bị vấn đề lag chữ gõ rất chậm và hay bị sai :(

**Comment by reun** [comment]
Mình mới phát hiện ra là do Coda chậm chứ không phải tại Openkey nha. Sorry đã làm phiền.

**Comment by tuyenvm** [comment]
Dạo này cv nên tối mình mới check lại hết issue. Coda là web app nên khó có thể can thiệp được @reun
