### ISSUE TITLE
Bỏ dấu hỏi tự do lỗi

### ISSUE THREAD

**Issue by kzjn10** [tuyenvm/OpenKey#17]
Lỗi khi gõ chử "hỉên" thị trong tiếng việt

**Comment by tuyenvm** [comment]
Bạn cập nhật bản 1.0.17 về dùng chế độ bỏ dấu kiểu cũ nhé.
Bỏ dấu tự do là kiểu cho mình nghĩ ra thôi nên nó còn lung tung lắm.
Không nên cho phép bỏ dấu tự do bạn nhé.

**Comment by kzjn10** [comment]
tks bạn, gõ ngon rồi.
