### ISSUE TITLE
Không gõ được tiếng Việt trên Google Docs, Google Sheets online

### ISSUE THREAD

**Issue by dungvu-qe** [tuyenvm/OpenKey#171]
Không gõ được tiếng Việt trên Google Docs, Google Sheets online.
Bên mình dùng ứng dụng văn phòng online, nhưng ko sử dụng được, bạn giúp với ạ. Các trường hợp khác hoạt động khá tốt.

**Comment by tuyenvm** [comment]
Bên bạn dùng trình duyệt gì?

**Comment by dungvu-qe** [comment]
mình dùng macos 10.15, safari 13

**Comment by tuyenvm** [comment]
Bạn thử bật tính năng "Gửi từng phím", sẽ ok nhé:
<img width="560" alt="Screen Shot 2020-06-18 at 2 06 04 PM" src="https://user-images.githubusercontent.com/7700801/84988871-f26c7580-b16c-11ea-81a3-54aa6f153a04.png">

Tham khảo thêm issue tương tự #89

**Comment by dungvu-qe** [comment]
ok mình sài được rồi, cảm ơn bạn đã hỗ trợ.
