### ISSUE TITLE
Is OpenKey discontinued?

### ISSUE THREAD

**Issue by kimkha** [tuyenvm/OpenKey#173]
It has been a while from the last commit, and many issues/PRs has been created without the maintainer's response.

 Also, if it's discontinued, does anyone fork it and still addressing some issues?

**Comment by tuyenvm** [comment]
No, OpenKey will never die.
I'm in the other project and will come back after finish it.
Thanks for interested 👍

**Comment by kimkha** [comment]
Thanks for fast response here. Love to see new updates coming. I will close this, btw.
