### ISSUE TITLE
Gõ @ thì bị biến thành ơ - Keyboard layout Japanese

### ISSUE THREAD

**Issue by tuyennq1001** [tuyenvm/OpenKey#18]
Hiện mình dùng Mac mua từ Nhật về, và phím @ thì nằm ngay bên trái phím [
Mỗi lần gõ @ thì sẽ bị hiện ra là ơ
Bạn có thể sửa lỗi này không?

Mình dùng OpenKey và thấy hay hơn GoTiengViet (bị lỗi khi dùng với Google Slides) và NAKL (cũng nguồn mở, nhưng ít cập nhật và bỏ dấu lộn xộn)

**Comment by tuyenvm** [comment]
Mình chuẩn bị release bản 1.0.17 có chế độ gõ SimpleTelex, bạn thử xem khắc phục được không nhé.

**Comment by tuyennq1001** [comment]
@tuyenvm perfect
Đã fix được rồi nhé. Thanks bạn.
