### ISSUE TITLE
Không gõ được ở layout bàn phím tiếng Đức

### ISSUE THREAD

**Issue by quochuywdm** [tuyenvm/OpenKey#181]
Ở bàn phím tiếng đức, chữ y và chữ z đổi chỗ cho nhau.
Khi gõ chữ y mặc dù nhận vào chữ y lên màn hình nhưng openkey lại đối xử với chữ y đó như chữ z (có vẻ như open key đang nhận dạng kys tự nhập vào dựa theo vị trí trên layout)

Nên các chữ có chữ y sẽ không thể gõ có dấu được. Vd:
kyx, kys nguyeenx

**Comment by tuyenvm** [comment]
um hiện OpenKey hoạt động dựa theo bàn phím tiêu chuẩn, mình sẽ xem lại và hỗ trợ nhiều layout bàn phím hơn.

**Comment by bachld97** [comment]
@quochuywdm Bạn build code ở PR #166 xài thử nhé.

**Comment by quochuywdm** [comment]
> @quochuywdm Bạn build code ở PR #166 xài thử nhé.

Sao vậz, hoa mỹ, hoa mỹ, chiếc thuzền, yên, yêu, bấy lâu nay, vay mượn, dấu phẩy.

Vẫn còn lỗi một số chỗ nhưng cám ơn rất nhiều và đã thể ý là fix bug

**Comment by quochuywdm** [comment]
sao vậz, chiếc thuzền, đưa đẩz..
Mình thử với bàn phím ABC - QWERTZ mà vẫn bị lỗi.
Mình đang dùng bàn phím magic keyboard của Apple

**Comment by bachld97** [comment]
@quochuywdm Mình confirm lại các bước bạn thực hiện xem có đúng chưa nhé, hiện mình chưa reproduce được trên bàn phím macbook (mình không có Magic Keyboard để test thử nhưng mình dùng nghĩ bàn phím nào không ảnh hưởng). Không biết có sai bước nào không.

1. Bật ABC - QWERTZ
2. Gõ các phím V, A, A, J, Z trên bàn phím 
3. Expectation: Hiện "vậy" trên màn hình. Thực tế: Hiện "vậz".

https://user-images.githubusercontent.com/28972708/104992375-7ebc7f00-5a53-11eb-94d3-b3904a706b84.mp4
