### ISSUE TITLE
OpenKeyHelper vẫn đang chạy nền Intel?

### ISSUE THREAD

**Issue by ngocphamm** [tuyenvm/OpenKey#189]
Hôm qua mới update app thấy ghi hỗ trợ M1, nhưng Activity Monitor vẫn báo có OpenKeyHelper chạy dưới kiến trúc Intel.

OpenKeyHelper có tác dụng gì, và liệu có thể được build cho kiến trúc Apple Silicon dược ko vậy?

![CleanShot 2021-01-29 at 20 40 30](https://user-images.githubusercontent.com/395123/106343201-3fbbd400-6272-11eb-9270-dfaffdcfe047.png)

**Comment by tuyenvm** [comment]
OpenKeyHelper là để giúp OpenKey chính chạy cùng macOS.
Bạn force quit OpenKeyHelper đi, tắt bật tính năng khởi động cùng macOS, khởi động lại máy là nó hết. OpenKeyHelper cũng sẽ chạy native m1

**Comment by ngocphamm** [comment]
Ra là vậy. Cảm ơn @tuyenvm nhiều nhé!
