### ISSUE TITLE
[MacOS M1] Thường xuyên không gõ được tiếng Việt trên MacOS Big Sur M1

### ISSUE THREAD

**Issue by duypham9895** [tuyenvm/OpenKey#193]
Bộ gõ thường bộ lỗi đơ, không gõ được tiếng Việt, mặc dù dùng phím tắt chuyển các ngôn ngữ gõ vẫn bình thường nhưng khi gõ lại không hoạt động. Mình đã reset máy vài cài lại OpenKey theo nhiều cách (tải file DMG, cài thông qua Brew,...) nhưng sử dụng được một thời gian (tầm 30 phút) thì bộ gõ lại bị đơ và không hoạt động được nữa. Mong nhà phát triển có thể fix lỗi này sớm. Nếu cần thiết thì ra một bản tính phí và fix các lỗi ấy. Mình sẵn sàng dùng phần mềm có phí để được fixx hết các lỗi khó chịu như trên.

**Comment by tuyenvm** [comment]
Máy chính của mình vẫn đang là Intel, có đợi 1 thời gian mình dùng máy M1 làm máy chính mới tìm ra nguyên nhân được.
Mà đợi mới mua máy M1 mình có trải nghiệm OpenKey cho M1 liên tục 3 ngày cũng không gặp bất kỳ tình trạng nào.
App bạn hay dùng là app gì nhỉ, có thể nó bị xung đột với những app đó.

**Comment by duypham9895** [comment]
App mình thường xuyên dùng nhất là Chrome, VSCode, Messages, Messenger, All-in-One Messenger. Khi OpenKey bị đơ thì tất cả các phần mềm đều không gõ được tiếng Việt luôn.

**Comment by duypham9895** [comment]
Máy hiện tại của mình là M1 thì bị tình trạng này, nhưng máy cũ Intel (MBP 15 2017) cũng bị luôn =((, khi hỏi những người dùng Macbook chung thì ít người bị hoặc có bị nhưng không thường xuyên và liên tục như mình.

**Comment by duypham9895** [comment]
Sau khi ngồi đọc lại các issues thì mình phát hiện bugs này là **do phần mềm Bitwarden**, nếu Bitwarden block thì sẽ không dùng OpenKey để gõ tiếng việt, unblock Bitwarden thì sẽ gõ đc bình thường.

Mong @tuyenvm sớm tìm ra cách giải quyết cho vấn đề bị đụng với phần Bitwarden này ạ.
Mình xin phép đc đóng issue này tại đây.

Cảm ơn @tuyenvm và mọi người nhé.
