### ISSUE TITLE
Chuyển bảng mã nhanh bằng phím tắt

### ISSUE THREAD

**Issue by notrealdev** [tuyenvm/OpenKey#195]
Chào các bạn, có cách nào để dùng phím tắt chuyển mã nhanh giữa 2 bảng mã ko nhỉ?
Ví dụ ở đây mình muốn chuyển qua lại giữa 2 mã TCVN3 ABC và Unicode

![Imgur](https://i.imgur.com/VOfHz5s.png)

**Comment by tuyenvm** [comment]
Hiện OpenKey chưa có tính năng chuyển mã bằng phím tắt, nhưng mình hiểu là đôi lúc mình hay đổi qua lại giữa các loại font chữ, có lẽ mình sẽ thêm tính năng này vào!

**Comment by notrealdev** [comment]
Cám ơn bạn!
