### ISSUE TITLE
Not compatible with mac os 10.13

### ISSUE THREAD

**Issue by nhaancs** [tuyenvm/OpenKey#2]
only support mac 10.14 or higher

**Comment by tuyenvm** [comment]
Will support it in next version, thanks for supporting. ^^

**Comment by khaintt** [comment]
Tác giả support luôn 10.12 cho cộng đồng không thích dùng mac os mới.

**Comment by tuyenvm** [comment]
Đã hỗ trợ macOS version cũ.
Chi tiết bạn xem tại: [Release](https://github.com/tuyenvm/OpenKey/releases)
