### ISSUE TITLE
Tạm tắt tính năng kiểm tra chính tả

### ISSUE THREAD

**Issue by tranhungdlk** [tuyenvm/OpenKey#20]
Cảm ơn bạn nhiều! Bản 1.0.17 đã tốt hơn rất nhiều rồi, là một người thường xuyên gõ văn bản, mình thêm 1 vài góp ý nha:

1. Chức năng **Kiểm tra chính tả** chưa hoạt động, có thể gõ những từ sai lènmsn như thế naỳm mà vẫn gõ được.

2. Khi bạn hoàn thiện chức năng **Kiểm tra chính tả**  thì mong bạn thêm cho lựa chọn nhấn phím Ctrl hoặc Command để tạm thời bỏ qua việc kiểm tra chính tả với 1 từ đó, nguyên nhân: Mình ở Đăk Lăk nên thường xuyên phải gõ các từ không có trong từ điển tiếng Việt như: Đăk Lăk, Krông Ana, M'đrắk, Ea H'đing, Yôk Yu, DrangFôk, Krông Knô... Đề xuất bạn có tùy chọn như Unikey hoặc Evkey để gõ những từ như vậy, cụ thể là: Khi muốn gõ chữ Krông thì gõ **Kr** rồi nhấn Ctrl (hoặc Command) nó sẽ tạm bỏ qua việc kiểm tra chính tả với 2 ký tự gõ trước, rồi gõ tiếp chữ **ông** để được chữ **Krông**

3. Có bạn đề xuất rồi nhưng mình muốn gom luôn vào 1 bài của mình để cho bạn dễ nhớ: Mong bạn hoàn thiện phần gõ tắt trong bản tiếp theo, cái này mình dùng khá nhiều vì thường xuyên gõ bị lỗi như: **cảu**, muốn nó tự sửa thành **của**, **tủng** thành **trung**... và tốc độ gõ sẽ cải thiện nhiều với các cụm từ thường xuyên gặp.

4. Một tính năng ít dùng nhưng thỉnh thoảng vẫn phải dùng khi lấy văn bản trên mạng về đó là **"Chuyển mã"**, các văn bản tải trên mạng có thể bảng mã là Unicode, VNI, TCVN3... để sử dụng trong cùng 1 văn bản thì cần phải chuyển về thống nhất thành Unicode. Nếu có thể bạn thêm phần này nữa nha!

5. Khi nào có thời gian, mong bạn Support các bản Mac OS thấp hơn để những người xài máy cũ, những người không thể hoặc không muốn nâng lên MacOS version >= 10.14 có bộ gõ tuyệt vời này để làm việc.

Bạn đã mang một luồng sinh khí mới cho cộng đồng yêu thích hệ điều hành Mac OS, chân thành cảm ơn bạn, chúc bạn luôn mạnh khỏe, hạnh phúc, thành công!

**Comment by tuyenvm** [comment]
Rất cảm ơn bạn, mình sẽ cố gắng cải tiến. 👍

**Comment by tuyenvm** [comment]
Mời bạn dùng thử bản 1.4 đã có tính năng chuyển mã :D.
Còn nôt tính năng `tạm thời tắt chính tả` nữa thôi là hoàn chỉnh ^^

**Comment by tuyenvm** [comment]
Đã thêm tính năng tạm thời tắt check chính tả bằng phím Ctrl.
VD: để gõ Krông, gõ Ctrl trước rồi gõ như bình thường.
Qua từ mới thì chính tả sẽ hồi phục.
Nhiều quá không biết còn thiếu tính năng nào không :D

**Comment by tranhungdlk** [comment]
Ad nhiệt tình quá! Cảm ơn ad nhiều vì đã hỗ trợ anh em, chịu khó lắng nghe ý kiến góp ý của người dùng. Một lần nữa chân thành cảm ơn ad!
