### ISSUE TITLE
Nên có option để bật tắt cách gõ tắt kiểu cũ `w => ư`

### ISSUE THREAD

**Issue by anhtran** [tuyenvm/OpenKey#208]
Mình thường xuyên viết code có tiếng việt trong các messages với các ký tự `[] ()` rất nhiều, chữ `w` cũng thường xuyên sử dụng. Bản thân mình không muốn dùng các kiểu viết tắt ép buộc như `w => ư` hay `[ => ơ` và cũng rất ít dùng. Mình nghĩ sẽ có nhiều người như vậy, nếu có option để bật tắt HOÀN TOÀN chuyện này thì quả là tuyệt vời luôn.

Cảm ơn OpenKey vì một project open source chất lượng!

**Comment by daohoangson** [comment]
Kiểu gõ Simple Telex nó bỏ cái `w` thành `ư` đó bạn.
