### ISSUE TITLE
Không gõ được chữ đ trên thanh địa chỉ của chrome

### ISSUE THREAD

**Issue by dinhtuan1991vt** [tuyenvm/OpenKey#22]
Gõ chữ đ không được nha bác. Luôn bị chuyển thành dđ :))

**Comment by tuyenvm** [comment]
lạ nhỉ em test hoài mà có bị đâu :D

**Comment by dinhtuan1991vt** [comment]
<img width="1030" alt="Screen Shot 2019-08-01 at 12 26 56 AM" src="https://user-images.githubusercontent.com/5716579/62233621-2161e780-b3f3-11e9-87a8-44d990992eac.png">
Cuối cùng cũng tìm được nguyên nhân. Em phải tắt cái `Sends some cookies and searches from the address bar and search box to your default search engine` này thì mới gõ chữ đ được. Bác thử xem sao nhé.

**Comment by n13minh** [comment]
> lạ nhỉ em test hoài mà có bị đâu :D

Confirmed, mình cũng không gặp lỗi này.

**Comment by tranhungdlk** [comment]
Chome của mình cũng không bị, có thể nào bạn đang xài gotiengviet chứ không phải OpenKey không nhỉ?

**Comment by dinhtuan1991vt** [comment]
@n13minh @tranhungdlk  Các bạn thử bật cái Sends some cookies and searches from the address bar and search box to your default search engine trong settings của Chrome xem có bị giống mình ko? Mình confirm là đang xài OpenKey nhé.

**Comment by n13minh** [comment]
FYI @dinhtuan1991vt: thiết lập **Autocomplete searches and URLs** đang bật (**ON**) mặc định trên Chrome của mình từ xưa đến giờ (mình đoán những người khác cũng vậy) và vẫn không gặp lỗi như của bạn.

![Screenshot at Aug 01 10-08-59](https://user-images.githubusercontent.com/12269399/62262928-a6c1b800-b444-11e9-95a2-1b53fa2969fc.png)

**Comment by dinhtuan1991vt** [comment]
@n13minh ok thanks bạn. Để mình check lại settings của Chrome mình xem sao.

**Comment by tranhungdlk** [comment]
@dinhtuan1991vt Mình cũng để setting mặc định, cái Autocomplete searches and URLs đang để ON, bạn thử cặp nhật OpenKey lên bản mới nhất + xóa chrome rồi cài lại xem sao

**Comment by dinhtuan1991vt** [comment]
@tranhungdlk ok thanks bạn. Để mình thử xem ^^.

**Comment by dinhtuan1991vt** [comment]
Hoá ra là do chrome của mình. Mình đã clear hết history và cache của chrome rồi khởi động lại và gõ được chữ đ ngon lành rồi =))
