### ISSUE TITLE
Chế độ tắt w --> ư

### ISSUE THREAD

**Issue by ptrinh** [tuyenvm/OpenKey#223]
Khi bật chế độ này, muốn viết chữ "ư" thì cần đánh "uw" thay vì "w".

Chế độ này sẽ giúp mình đỡ mất công bật/tắt tiếng Việt khi gõ tiếng Anh nhiều vì tiếng Anh có rất nhiều từ bắt đầu bằng w.

**Comment by dangh** [comment]
Ban dung Simple Telex no khong co uw voi ]

**Comment by ptrinh** [comment]
oh chuẩn rồi. Cảm ơn bạn nhé!
