### ISSUE TITLE
Không tiếp tục gõ tiếng việt được sau khi nhấn space rồi back lại

### ISSUE THREAD

**Issue by ductranit** [tuyenvm/OpenKey#23]
Mình thấy có 1 issue khá rõ so với GoTiengViet ở chỗ gõ thiếu/sai dấu hoặc bấm nhầm space thì quay lại (backspace) ko sửa được, phải xoá hết từ đó gõ lại. Trong khi GoTiengViet cho sửa thoải mái. 
Ví dụ như khi muốn gõ "không" (kiểu VNI) nhưng nhầm thành "khọng ", nhấn backspace để xoá space và gõ "6" thì nó thành "khọng6" chứ ko phải "không" như GoTiengViet
Bạn xem rồi fix dùm nhé.
Thanks!

**Comment by tuyenvm** [comment]
Bạn cập nhật bản 1.0.17 chưa? bản mới đã khắc phục lỗi này rồi đó bạn.

**Comment by ductranit** [comment]
à, thank bạn. Đã work :D
