### ISSUE TITLE
[Thêm tính năng] Không chuyển sang tiếng Việt khi đang gõ tiếng Nhật/Trung... bằng Microsoft IME

### ISSUE THREAD

**Issue by vungoctrung93** [tuyenvm/OpenKey#236]
Nhờ vào việc phát hiện IME pad có đang bật lên hay không mà xác định có đang gõ tiếng Nhật/Trung hay không?

Code:
File win32\OpenKey\OpenKey\OpenKey.cpp, trong hàm keyboardHookProcess.

`
#pragma region Contributed by vungoctrung93

#pragma comment(lib, "imm32")
#define IMC_GETOPENSTATUS 0x0005
    HWND hWnd = GetForegroundWindow();
    HWND hIME = ImmGetDefaultIMEWnd(hWnd);
    LRESULT isImeON = SendMessage(hIME, WM_IME_CONTROL, IMC_GETOPENSTATUS, 0);
    if (isImeON) {
        return CallNextHookEx(hKeyboardHook, nCode, wParam, lParam);
    }
#pragma endregion
`

**Comment by kienmatu** [comment]
Tự nghiên cứu làm luôn a, code thì anh thêm "```" nó mới nhận format code ạ.
Hình như anh đã làm luôn rồi sao anh k open pull request?

**Comment by vungoctrung93** [comment]
Anh build tự dùng ở máy rồi Kiên. Anh bấm vào format code ở git nó ra mỗi `` rồi anh viết vào giữa mà không thấy nó nhận.
Để anh tạo pull request thử.

**Comment by vungoctrung93** [comment]
Đã merge bởi:


https://github.com/tuyenvm/OpenKey/pull/238
