### ISSUE TITLE
Không gõ được W trên thanh Spotlight search khi đang để chế độ gõ tiếng Việt

### ISSUE THREAD

**Issue by bqthien1011** [tuyenvm/OpenKey#246]
Tôi muốn gõ chữ WRAP. Nhấn W hai lần nhưng không tự động xoá Ư

<img width="909" alt="image" src="https://github.com/tuyenvm/OpenKey/assets/12619263/7f69caed-62e3-49df-aeaa-5de9f553e8e0">

**Comment by ln8711** [comment]
issue này có rồi bạn, bạn nên đóng lại rồi qua đây https://github.com/tuyenvm/OpenKey/issues/237
