### ISSUE TITLE
Security & Privacy concern

### ISSUE THREAD

**Issue by nit27** [tuyenvm/OpenKey#248]
Hi Tuyen,
I am very impressive on your product. Recently, I have some issues when typing Vietnamese (TELEX built-in) on [Sublimetex](https://www.sublimetext.com/) so that I am about to switch to your OpenKey as I found that  your app could fix some annoying Vietnamses typing issue on MacOS. I just, however, have a question that where can I see the `Terms & Conditions` of using your app that could reflect security & privacy regarded? I really take care of keeping away from keylogger and unneccessary analytic tracking machanism to the developers.

<img width="372" alt="Screenshot 2023-12-18 at 10 17 14" src="https://github.com/tuyenvm/OpenKey/assets/95131051/f494ac88-f66f-4ff1-96d8-39e55adbc3d6">

Thank you.

**Comment by tuyenvm** [comment]
Hi,
I built OpenKey from source code base on this repo, **No Keylogger, no backdoor, no analytic.**
I understand your concerns about this software's behavior, no T&C at this time, but you can use source code on this repo to build OpenKey by yourself.

**Comment by nit27** [comment]
Nice,  thanks for your response. I will try to build it from yours. That's awesome!
