### ISSUE TITLE
Lỗi không bỏ dấu khi có dấu ( ở phía trước

### ISSUE THREAD

**Issue by tuyennq1001** [tuyenvm/OpenKey#26]
Khi mình muốn gõ 
`(hình như là`
thì sẽ bị biến thành
`(hinhf như là`

Tương tự khi gõ dạng `đặc sản` sẽ bị thành `ddawjc sản`
Nhờ bạn fix giúp nhé

**Comment by causelove94** [comment]
mình cũng gặp lỗi này, không phải lúc nào cũng bị mà có lúc đc lúc ko. Nhưng mình phát hiện ra là tắt tính năng "Kiểm tra chính tả" đi thì tạm thời khắc phục đc.

**Comment by tuyenvm** [comment]
Bản sau sẽ khắc phục nhé bạn, đúng là do tính năng kiểm tra chính tả.
Và nữa là do bàn phím tiếng Nhật nên mã phím nó khác hoặc bị xê dịch so với bàn phím tiêu chuẩn.
