### ISSUE TITLE
Lỗi khi gõ vào Address bar của Chrome 

### ISSUE THREAD

**Issue by tuyennq1001** [tuyenvm/OpenKey#27]
Không chắc lắm là có sửa được không vì mình thấy nhiều bộ gõ cũng gặp lỗi này 

**Tái hiện**
Khi muốn gõ `đặc sản` vào Address bar của Chrome thì sẽ có 1 chữ d xuất hiện phía trước 

![image](https://user-images.githubusercontent.com/747698/62265457-5ea79300-b44e-11e9-9bc2-cd6c7a0df5b7.png)

**Kỳ vọng**
Gõ `đặc sản` thì ra `đặc sản` luôn

**Comment by dinhtuan1991vt** [comment]
@tuyennq1001 Bạn thử clear hết history và cache của chrome rồi thử lại xem sao nhé. Mình cũng đã từng bị giống vậy.

**Comment by n13minh** [comment]
Trước đây mình luôn gặp lỗi này khi dùng GoTiengViet của TKN, từ khi chyển qua OpenKey thì đã hết bị. Lỗi này khá khó chịu, vì đa số mọi người khi dùng Chrome đều sẽ search trực tiếp từ thanh địa chỉ.

**Comment by orekasep** [comment]
Hiện tại vẫn bị. 

Chrome: 75.0.3770.142
MacOS 10.14.5

**Comment by tuyenvm** [comment]
Mình sẽ fix triệt để lỗi này cho riêng Chrome trong bản sau ;)

**Comment by nguyenrom** [comment]
@tuyennq1001 mình không bị chữ **đ** nhưng bị chữ **gói** = **goói**

Cho trường hợp:
https://i.imgur.com/tmllZLu.png

Hôm nay mới bị trường hợp bật OpenKey nhưng vẫn không gõ tiếng Việt được dù có thoát ra vào lại, mình bật VNI của mặc định của Mac sau đó bật lại OpenKey để gõ thì lại gõ được mà không rõ vì sao.

**Comment by tuyennq1001** [comment]
Thấy đã được fix ở v1.2 nên mình close cái này
