### ISSUE TITLE
Lỗi khi gõ chữ g i f

### ISSUE THREAD

**Issue by tuyennq1001** [tuyenvm/OpenKey#28]
Hiện tại không gõ được chữ `gì` => cụ thể là không có dấu huyền

**Comment by causelove94** [comment]
Mình cũng gặp phải lỗi này, ko chỉ chữ `gì` mà chữ `gi` khi gõ với bất kì dấu nào cũng ko lên dấu. Bạn @tuyenvm fix nhé!

**Comment by tuyenvm** [comment]
bạn @causelove94 cũng dùng bàn phím Tiếng Nhật hả?

**Comment by causelove94** [comment]
> bạn @causelove94 cũng dùng bàn phím Tiếng Nhật hả?

ko bạn ạ, máy mình bàn phím quốc tế (ko phải bàn phím của Nhật hay châu Âu đâu)

**Comment by ansidev** [comment]
@tuyennq1001 Duplicate of https://github.com/tuyenvm/OpenKey/issues/25

**Comment by mrnvdong** [comment]
mình cũng không gõ được chữ gi

**Comment by AloneRoad** [comment]
mình cũng không gõ được chữ `gì`, nhưng khi bật "Đặt dấu oà uý (thay vì òa, úy)" lên thì gõ được 

macOS Mojave version 10.14.6 (18G84)

**Comment by mrnvdong** [comment]
> mình cũng không gõ được chữ `gì`, nhưng khi bật "Đặt dấu oà uý (thay vì òa, úy)" lên thì gõ được
> 
> macOS Mojave version 10.14.6 (18G84)

Mình đã thử theo cách của bạn và gõ được.
Cám ơn bạn gì nhé :D

**Comment by causelove94** [comment]
> mình cũng không gõ được chữ `gì`, nhưng khi bật "Đặt dấu oà uý (thay vì òa, úy)" lên thì gõ được
> 
> macOS Mojave version 10.14.6 (18G84)

Đúng là bật "Đặt dấu kiểu oà uý" thì gõ chữ **gì** ko bị lỗi nữa. Mong bạn @tuyenvm xem xét lỗi tại trường hợp này để fix nhé, vì mình hay dùng kiểu `òa, úy` hơn. Đặt dấu kiểu `oà, uý` ko phổ biến bằng nên sẽ gặp trở ngại khi tìm kiếm, truy vấn trong word, excel.

**Comment by tuyenvm** [comment]
mình xác nhận có lỗi này kho bỏ dấu kiểu cũ "òa, úy", sẽ sửa trong bản tiếp theo.

**Comment by tuyenvm** [comment]
đã fix trong bản [1.0.19](https://github.com/tuyenvm/OpenKey/releases)
