### ISSUE TITLE
Lỗi hiển thị dấu

### ISSUE THREAD

**Issue by nguyenrom** [tuyenvm/OpenKey#3]
Đầu tiên mình rất cảm ơn bạn Tuyen Mai về ứng dụng này!

Có một số lỗi mình phát hiện được khi dùng thử:

1/ Các chữ bị lệnh vị trí dấu: ch**ịên**, ngh**ịêp**, tr**íêt**, ng**ừơi** v.v.
2/ Gõ (Shift + số 1-!, 6-^, 9-đ, v.v.) sau khi kết thúc chữ tự mất dấu, không nhận biết được ký tự bổ sung.

Mình đang dùng **10.14.6**
Thân,
Nguyen

**Comment by nguyenrom** [comment]
Minh hoạ: https://www.loom.com/share/44c5066a16a14ba69a22c5a2e3a55607

**Comment by tuyenvm** [comment]
Cảm ơn bạn đã dùng thử và báo bug, mình sẽ update bản sửa lỗi sớm.

**Comment by nguyenrom** [comment]
@tuyenvm , mình update thêm: 

Chữ đầu tiên in hoa không thể gõ dấu ở VNI.
- O6
- U7
- etc.
