### ISSUE TITLE
Lỗi : khó chịu khi dùng slack

### ISSUE THREAD

**Issue by huyvl102** [tuyenvm/OpenKey#30]
Hi bạn,
Mình đang dính lỗi thường hay gõ chat với icon . Ví dụ : không chạy http.get :D 
thì icon luôn nhảy vào giữ get->g:Det rất khó chịu
Mong bạn fix , cảm ơn rất nhiều . Tool rất hữu dụng

**Comment by tuyenvm** [comment]
Lỗi khá lạ, bạn có thể record video giúp mình được không?

**Comment by huyvl102** [comment]
Vào slack gõ như sau : "em check lỗi như thế này :sw" , khi gõ :sw nó hiện gợi ý icon , tick chọn icon quả khoai tây ấn enter sẽ hiện bug
