### ISSUE TITLE
Tính năng: ẩn/hiện biểu tượng trên thanh dock

### ISSUE THREAD

**Issue by buianhthang** [tuyenvm/OpenKey#32]
Chào bạn,

Mình thấy ko cần thiết phải hiện biểu tượng ở trên thanh dock, bạn thêm tính năng này cho app nhé

**Comment by tuyenvm** [comment]
Đã có trong bản 2.0.1, thanks bạn ^^

**Comment by buianhthang** [comment]
@tuyenvm khi mình chọn "Hiện biểu tượng trên thanh dock", sau đó bỏ chọn thì bảng điều khiển biến mất. Người dùng sẽ muốn bảng điều khiển vẫn hiển thị hơn là biến mất luôn. Hoặc có thể đây là bug :D

**Comment by tuyenvm** [comment]
Khác với Unikey, user tùy chỉnh cho sướng rồi đóng bảng điều khiển mới có tác dụng, còn OpenKey thì có tác dụng tức thì nên khi ẩn icon trên thanh Dock thì bảng điều khiển cũng hide luôn theo cơ chế của macOS :D
