### ISSUE TITLE
Lỗi: khởi động cùng macOS không hoạt động

### ISSUE THREAD

**Issue by buianhthang** [tuyenvm/OpenKey#33]
Mình đang dùng macOS Catalina 10.15 beta thì thấy tính năng này ko hoạt động. Bạn kiểm tra xem nhé

Update thêm chi tiết:
Khi khởi động thì có biểu tượng ở thanh dock, trên menu bar ko có. Phải nhấn vào biểu tượng ở thanh dock để hiển thị cửa sổ, sau đó nhấn OK thì mới hiển thị trên menu bar và họat động được

**Comment by dungvu-qe** [comment]
đúng rồi bạn nhé, lần đầu bật nó lên còn gây treo nguyên máy. phải restart mới chạy đc. nhưng lại chạy rất tốt nên ko phàn nàn nữa. Đến khi đọc ở đây :)

**Comment by tranhungdlk** [comment]
Xác nhận Open key không tự khởi động cùng High Sierra 10.13.6! Mong tác giả sẽ fix trong bản kế tiếp

Trân trọng cảm ơn!

**Comment by tuyenvm** [comment]
Bản update mới cho macOS 2.0.1 đã khắc phục hoàn toàn vấn đề khởi động cùng macOS rồi nhé các bạn, chạy ok với macOS 10.13 cũ.
Rất xin lỗi vì đã để vấn đề này lâu đến vậy.
