### ISSUE TITLE
Lỗi gõ chữ ưúong, uúông

### ISSUE THREAD

**Issue by ga4so9** [tuyenvm/OpenKey#36]
Khi mình gõ các chữ ưúong theo thứ tự các phím sau: w u o n g s, đúng ra nó sẽ phải ra chữ ưuongs.
Tương tự gõ chữ uúông theo thứ tự phím: w u o o n g s, đúng ra là phải ra chữ ưuoongs.
Mình nghĩ là do phần kiểm tra chính tả chưa hoạt động tốt. Ngoài ra, khi có tính năng khôi phục phím với từ sai thì nó sẽ ra đúng các phím mình đã nhấn.
Bạn kiểm tra lại nhé.
À mình dùng Telex nhé

**Comment by tuyenvm** [comment]
Bản 1.1 có tính năng hồi phục phím với từ sai, bạn check thử nhé.

**Comment by ga4so9** [comment]
mình dùng thử thì tính năng này chỉ hoạt động khi bấm phím Space sau từ sai. Bạn update thêm là bấm các phím như ngắt câu như chấm, phẩy, chấm phẩy... thì cũng khôi phục phím với từ sai nhé

**Comment by tuyenvm** [comment]
ok bạn, mình sẽ thêm vào trong bản sau.

**Comment by tuyenvm** [comment]
đã cập nhật thêm trong bản 1.2 mới nhé.
