### ISSUE TITLE
Không gõ được tiếng Việt trên Safari

### ISSUE THREAD

**Issue by tuyennq1001** [tuyenvm/OpenKey#38]
Đang bị lỗi trên Safari: gõ trên Address bar thì OK, nhưng trong Facebook, Messenger hay Github thì đều bị lỗi như dưới đây

[![Image from Gyazo](https://i.gyazo.com/84ddd8e7efdf7933ca691f0db956efe7.gif)](https://gyazo.com/84ddd8e7efdf7933ca691f0db956efe7)

Mac OS 10.14.5
MacBook Air
Safari 12.1.1

Confirm giúp mình nhé

**Comment by tuyenvm** [comment]
bạn có đang bật bộ gõ khác không?, thậm chí để chế độ Tiếng Anh cũng không được, mình đang gõ bằng OpenKey luôn.

**Comment by khanhcan148** [comment]
Hịên tại mình dính lỗi như hình trên. Nếu bạn gõ vieejt = việt, vijeet = vịêt

**Comment by tuyennq1001** [comment]
> bạn có đang bật bộ gõ khác không?, thậm chí để chế độ Tiếng Anh cũng không được, mình đang gõ bằng OpenKey luôn.

Minh dang dung bo go cua Google => Google Japanese Input, che do Alphanumeric

**Comment by causelove94** [comment]
@tuyennq1001, em vừa thử add thêm layout tiếng Nhật Romaji kia của bác thì đúng là bị lỗi như bác nói thật. Vậy bác vào `System Preferences`/`Keyboard`/`Input Sources` add thêm layout `English`/`ABC` như hình dưới là sẽ xử lí đc lỗi nhé!
![Screen Shot 2019-08-04 at 21 40 58](https://user-images.githubusercontent.com/18412705/62425136-bc173a80-b701-11e9-89cd-be4fe9ca878d.png)

**Comment by tuyennq1001** [comment]
> @tuyennq1001, mình vừa thử thêm layout tiếng Nhật `Romaji` kia thì đúng là bị lỗi như bạn gặp phải. Vậy bạn vào `System Preferences`/`Keyboard`/`Input Sources`, thêm layout `English`/`ABC` như hình dưới rồi sử dụng nó là sẽ xử lí đc lỗi nhé!
> ![Screen Shot 2019-08-04 at 21 40 58](https://user-images.githubusercontent.com/18412705/62425136-bc173a80-b701-11e9-89cd-be4fe9ca878d.png)

OK rồi nhé :)

**Comment by quangp49** [comment]
> @tuyennq1001, mình vừa thử thêm layout tiếng Nhật `Romaji` kia thì đúng là bị lỗi như bạn gặp phải. Vậy bạn vào `System Preferences`/`Keyboard`/`Input Sources`, thêm layout `English`/`ABC` như hình dưới rồi sử dụng nó là sẽ xử lí đc lỗi nhé!
> ![Screen Shot 2019-08-04 at 21 40 58](https://user-images.githubusercontent.com/18412705/62425136-bc173a80-b701-11e9-89cd-be4fe9ca878d.png)
bác @causelove94  ơi em bị lỗi y như bác @tuyennq1001 nhưng làm theo hướng dẫn của bác thì k được huhu
