### ISSUE TITLE
Tổ chức folder source code

### ISSUE THREAD

**Issue by nhymxu** [tuyenvm/OpenKey#4]
Không nên để binary release ở git source.
Github có mục release. Mỗi lần ra phiên bản có thể upload binary file ở đó + ghi changelog

Mình góp ý xíu vậy thôi

**Comment by tuyenvm** [comment]
cảm ơn bạn, mình sẽ rút kinh nghiệm.

**Comment by luongvo** [comment]
@tuyenvm issue nào đã resolve bạn có thể close luôn để ae dễ theo dõi. Cảm ơn :)
