### ISSUE TITLE
Tự động chuyển sang tiếng Anh/tiếng Việt khi chuyển giữa các ứng dụng được thiết lập sẵn.

### ISSUE THREAD

**Issue by ansidev** [tuyenvm/OpenKey#40]
Vấn đề:
- Người dùng luôn gõ tiếng Anh/tiếng Việt trong một số ứng dụng nhất định.

Yêu cầu tính năng:
- Cho phép định nghĩa rule để tự động chuyển sang tiếng Anh/tiếng Việt nếu người dùng switch từ một ứng dụng khác sang ứng dụng đó.
- Nếu người dùng switch từ ứng dụng đó sang một ứng dụng khác mà ứng dụng mới switch sang không có rule nào được định nghĩa thì chuyển lại tiếng được chọn trước khi các rule được áp dụng.
- Người dùng vẫn có thể chuyển giữa E-V trong các ứng dụng đã định nghĩa rule để override rule.

Ví dụ:
- Có các ứng dụng A, B.
- Người dùng thiết đặt tự động gõ tiếng Anh trong A (mode = E).
- Người dùng đang sử dụng ứng dụng B và chế độ là tiếng Việt (mode = V)
  + Switch sang A: mode = E.
  + Switch từ A sang B: mode = V.

**Comment by reun** [comment]
Mình nghĩ tính năng này sẽ rất hữu ích mà chưa thấy các bộ gõ khác có. 

Ngoài việc trên ứng dụng, mình nghĩ nên đi sâu vào từng tab trang web luôn, vì thực tế có rất nhiều ứng dụng chạy trên trình duyệt: VD: Zalo web, Messenger, Hangout, Google docs...

**Comment by tuyenvm** [comment]
các bạn thử bản 1.2 mới nhé, sử dụng tính năng "Chuyển chế độ thông minh", giống như @ansidev Miêu tả 99%

**Comment by Phamthai111** [comment]
Việt Nam

**Comment by Bangnguyen93** [comment]
Mode = v

**Comment by phat1904** [comment]
Thế có cách nào để chuyển giao diện tiếng anh của git sang hết tiếng việt hay không ạ.

**Comment by ansidev** [comment]
> Thế có cách nào để chuyển giao diện tiếng anh của git sang hết tiếng việt hay không ạ.

Trước tiên, hãy đặt câu hỏi đúng chỗ.

**Comment by Haohanhoaiduc007** [comment]
Ok

**Comment by Tine-MT** [comment]
là nhập ở đâu vậy mọi người
__

**Comment by kaiksb** [comment]
Rule
