### ISSUE TITLE
Kiểm tra phiên bản mới và tự động cập nhật

### ISSUE THREAD

**Issue by lizhiquan** [tuyenvm/OpenKey#42]
Chào bạn,

Như tiêu đề, bạn có thể thêm tính năng tự động kiểm tra cập nhật định kì cho ứng dụng. Như vậy người dùng không cần phải vào trang github để check và so sánh version thủ công.

Mình thấy đa phần các ứng dụng hiện nay sử dụng lib này: https://sparkle-project.org

Cảm ơn bạn.

**Comment by orekasep** [comment]
Vote +1

**Comment by hoangnamitc** [comment]
Hiện tại vẫn chưa có kiểm tra cập nhật trong ứng dụng, tuy nhiên vẫn có thể dùng thông báo từ github để biết khi nào có version mới. Không cần vào check thủ công.

![image](https://user-images.githubusercontent.com/7042462/62548348-d6335300-b890-11e9-8447-7b2593e167ec.png)

**Comment by tuyenvm** [comment]
Đã thêm tính năng cập nhật tự động trong bản [1.3 RC1](https://github.com/tuyenvm/OpenKey/releases).
Mời các bạn dùng thử.

**Comment by hoangnamitc** [comment]
![image](https://user-images.githubusercontent.com/7042462/64010944-e44d5a00-cb44-11e9-8474-197727014baa.png)

Mới thấy mail báo có cập nhật vào check thì ko đc. Tính năng này chưa xài đc à ad?

**Comment by tuyenvm** [comment]
file version.json raw trên github vẫn cache, đợi thêm thời gian nó mới update live được :D 
https://raw.githubusercontent.com/tuyenvm/OpenKey/master/version.json

**Comment by tuyenvm** [comment]
Mới check lại thì thấy nó live rồi, tính năng AutoUpdate hoạt động khá ổn :D
