### ISSUE TITLE
Sửa dấu khi bấm space và gõ chữ

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#43]
Sau khi bấm space và gõ 1 ký tự tiếp theo thì không quay lại sửa dấu được. Gotiengviet thì vẫn sửa được bình thường.

VD: "gõ co dấu" --> quên bỏ dấu chữ "có" và khi xóa chữ "dấu" để quay lại sửa thì không được.

Do mình gõ với tốc độ khá nhanh nên việc này diễn ra khá thường xuyên, mỗi lần vậy phải xóa hết nguyên chữ rồi gõ lại từ đầu.

Mình đang dùng phiên bản mới nhất là 1.0.19.

PS: rất cảm ơn bạn đã viết Openkey và update rất thường xuyên, đây là phần mềm gõ tiếng Việt mình thấy hài lòng nhất từ lúc xài Mac đến giờ. Khi nào bạn có tính năng donate chắc chắn mình sẽ ủng hộ.

**Comment by tuyenvm** [comment]
Cảm ơn bạn đã ủng hộ, mình sẽ update dần các tính năng mà mọi người cần. 👍

**Comment by reun** [comment]
Hiện tại với phiên bản mới nhất là 1.1 mình thấy Openkey đã đầy đủ tính năng (so với các bộ gõ khác) và chạy cũng ổn định rồi. 
Chỉ còn mỗi tính năng mình đề cập ở đây này là còn thiếu so với Gotiengviet, tính năng cũng nhỏ thôi nhưng làm mình hơi kém tự tin khi gõ, sợ gõ sai mà lỡ gõ chữ tiếp theo xong là không quay lại sửa được.

Hi vọng bạn sẽ sớm ra mắt tính năng này.

**Comment by tuyenvm** [comment]
tính năng này mình sẽ update trong bản 1.2 sau bạn nhé, mình thấy tính năng này cũng rất hữu ích.

**Comment by reun** [comment]
Đã thấy tính năng trên bản 1.3.2. Tuyệt vời ông mặt trời!

**Comment by tuyenvm** [comment]
đang tính vào thông báo cho bác mà tìm hoài không thấy thì ra là đã close :D
