### ISSUE TITLE
Lỗi remove openkey khỏi dock, nhưng khi cho start Openkey khi start OS thì nó vẫn hiện 

### ISSUE THREAD

**Issue by khanhvu14** [tuyenvm/OpenKey#44]
<img width="1440" alt="Screen Shot 2019-08-05 at 8 09 44 AM" src="https://user-images.githubusercontent.com/4197632/62432227-c31d6780-b758-11e9-950d-1fa0b3a54abc.png">
Vẫn hiện sau mỗi lần khởi động, dù đã "remove from dock"

**Comment by tuyenvm** [comment]
Bạn cũng đang dùng macOS Catalina nhỉ?

**Comment by khanhvu14** [comment]
Mình vẫn đang dùng Mojave.

**Comment by tuyenvm** [comment]
ah do dock mình tắt "show recen app" nên trước giờ nó không hiện.

**Comment by tuyenvm** [comment]
bạn thử lại với bản 1.0.20 xem sao nhé

**Comment by khanhvu14** [comment]
Ok rồi bạn nhé.
