### ISSUE TITLE
Chưa lưu lại setting cũ sau mỗi lần update.

### ISSUE THREAD

**Issue by khanhvu14** [tuyenvm/OpenKey#45]
<img width="648" alt="Screen Shot 2019-08-05 at 8 16 08 AM" src="https://user-images.githubusercontent.com/4197632/62432344-5e164180-b759-11e9-815b-e6c0896db533.png">
Mỗi lần update là phải chỉnh lại.

**Comment by tuyenvm** [comment]
Có thể mình build dạng non-sanbox để hỗ trợ cho cả macOS cũ nên nó tạo profile mới.
Từ bản này về sau nó đều giữ setting cũ.
