### ISSUE TITLE
Bị đổi chế độ gõ mỗi lần highlight chữ

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#46]
Mình để phím tắt để chuyển chế độ gõ là Shift + Command.
Mỗi lần cần highlight chữ mình sẽ dùng Shift + Command + Arrow right (hoặc left), và mỗi lần vậy thì lại đổi chế độ gõ. Bên Gotiengviet thì không bị vấn đề này.

**Comment by causelove94** [comment]
@tuyenvm vấn đề này có lẽ do bạn bắt sự kiện `keydown` là thực hiện đổi chế độ gõ nên bị như thế. Mình nghĩ nên bắt sự kiện `keyup` thì ổn hơn (tức là khi nhả phím ra mới chạy lệnh) thì vấn đề trên sẽ đc giải quyết.

**Comment by tuyenvm** [comment]
chuẩn luôn bạn 👍

**Comment by tuyenvm** [comment]
đã fix ở bản 1.0.20 mới rồi nha bạn ^^

**Comment by reun** [comment]
Cảm ơn bạn, mình vừa tải về cài xong, thấy ngon lành rồi. Đã ủng hộ cà phê cho bạn qua TK ngân hàng. Tiếp tục phát triển ứng dụng hữu ích này nha.

**Comment by tuyenvm** [comment]
@reun rất cảm ơn bạn đã ủng hộ và hỗ trợ mình 👍
