### ISSUE TITLE
Cho phép gõ chữ Đ ngay sau phụ âm

### ISSUE THREAD

**Issue by causelove94** [tuyenvm/OpenKey#48]
Mình hay gặp các từ viết tắt có chữ Đ đứng sau phụ âm như SĐT, QĐ, NĐ,... nên mình mong bạn có thể bổ sung trường hợp gõ này để thuận tiện hơn (bên UniKey cũng hỗ trợ điều này). Cảm ơn bạn rất nhiều!

**Comment by dinhtuan1991vt** [comment]
@causelove94 Bạn thử uncheck cái Kiểm tra chính tả là gõ được nhé

**Comment by causelove94** [comment]
> @causelove94 Bạn thử uncheck cái Kiểm tra chính tả là gõ được nhé

tắt "kiểm tra chính tả" thì cũng đc nhưng thi thoảng gõ mấy từ tiếng Anh xen vào thì lại hơi loạn bạn ạ. Mình nghĩ bổ sung trường hợp trên thì vẫn hơn, vì cơ bản nó vẫn đúng chính tả tiếng Việt.

**Comment by tuyenvm** [comment]
Mình sẽ bổ sung trường hợp này ngay cả khi check kiểm tra chỉnh tả.

**Comment by tuyenvm** [comment]
đã fix ở bản 1.0.20 mới rồi nha bạn ^^
