### ISSUE TITLE
Yêu cầu tính năng - Tự động bật tắt khi chuyển cửa sổ

### ISSUE THREAD

**Issue by tuanpmt** [tuyenvm/OpenKey#49]
Cám ơn cái App hữu ích này nhé Tuyên, đỡ hơn bộ gõ mặc định nhiều.

Mình hay chuyển từ cửa sổ trình duyệt sang cửa sổ code (sublime) - Code thì ko dùng tiếng Việt nữa, có thêm chế độ tự động bật tắt khi chuyển sang 1 cửa sổ ứng dụng nào đó thì tuyệt vời.

Đã mời coffee nhé, thanks

**Comment by tuyenvm** [comment]
Cảm ơn bạn ly caffee đá nhé ^^, tính năng này rất thiết thực, mình sẽ thêm vào trong các bản sau.

**Comment by tuyenvm** [comment]
bạn cập nhật bản 1.2, sử dụng tính năng: "Chuyển chế độ thông minh" nhé, ở sublime tắt tiếng Việt thì qua ứng dụng khác bật tiếng Việt, khi về sublime nó sẽ tự tắt tiếng Việt cho bạn.

**Comment by causelove94** [comment]
> bạn cập nhật bản 1.2, sử dụng tính năng: "Chuyển chế độ thông minh" nhé, ở sublime tắt tiếng Việt thì qua ứng dụng khác bật tiếng Việt, khi về sublime nó sẽ tự tắt tiếng Việt cho bạn.

2 tính năng mới của bản 1.2 hay quá bạn. Đúng là chuyển chế độ thông minh, tự ghi nhớ lựa chọn của từng ứng dụng, quá tiện lợi luôn. Tính năng viết hoa sau dấu chấm cũng rất tuyệt, 1 tính năng cứ ngỡ chỉ có trên điện thoại thì giờ đã dùng đc trên máy tính. Một lần nữa cảm ơn bạn @tuyenvm

**Comment by tuanpmt** [comment]
chờ đợi tính năng này hết cả thanh xuân mới có ngừơi làm, đã test chạy ngon lành 🎉🎉🎉

Xin phép mời thêm ly cafe sữa cám ơn nhé
