### ISSUE TITLE
Cho người dùng thiết lập tổ hợp phím để chuyển giữa tiếng Anh và tiếng Việt

### ISSUE THREAD

**Issue by tampham47** [tuyenvm/OpenKey#5]
Trước giờ mình dùng trình gõ mặc định của Mac, quen chuyển bằng cụm phím khác, nhưng khi dùng với OpenKey thì chưa được tuỳ biến cụm phím chuyển đổi này. 

Btw, nếu cần website để giới thiệu sản phầm thì mình có thể giúp, và deploy bằng `gh-pages`. 😁

PS/ Mình đang gõ với phần mềm OpenKey, phần mềm rất tốt, cảm ơn bạn nhiều.

**Comment by tuyenvm** [comment]
Cảm ơn bạn đã sử dụng phần mềm.
Mình sẽ thêm tính năng này sớm. 😍

**Comment by nmtrung** [comment]
> Cảm ơn bạn đã sử dụng phần mềm.
> Mình sẽ thêm tính năng này sớm. 😍

@tuyenvm làm sớm nha tình yêu

**Comment by tuyenvm** [comment]
Cập nhật bản mới 1.0.17 nha các bạn

**Comment by nmtrung** [comment]
> Cập nhật bản mới 1.0.17 nha các bạn

Mãi yêu
