### ISSUE TITLE
Lỗi: không dùng được phím tắt Emoji khi để Ctrl + Space

### ISSUE THREAD

**Issue by dinhquochan** [tuyenvm/OpenKey#50]
Dear,

Mình không biết các bạn có bị hay không, thì khi mình để phím tắt là <kbd>Ctrl</kbd> +<kbd>Space</kbd> thì đồng nghĩa khi bấm <kbd>Ctrl</kbd> + <kbd>Cmd</kbd> + <kbd>Space</kbd> đều chuyển ngôn ngữ Việt - Anh. Điều đó gây ra việc phím tắt Emoji không dùng được vì xung đột <kbd>Ctrl</kbd> + <kbd>Cmd</kbd> + <kbd>Space</kbd>.

Mình thử tắt OpenKey thì sử dụng bình thường. Và mình thử dổi phím tắt khác thì không bị, hiện mình mới phát hiện ở <kbd>Ctrl</kbd> +<kbd>Space</kbd> là bị thôi.

**Comment by starptit** [comment]
Đồng ý, mình recommend nên để `Cmd` + `Shift` thì sẽ hợp lý hơn.

**Comment by tuyenvm** [comment]
Mình sẽ sửa lỗi ngay trong bản sau bạn nhé

**Comment by tuyenvm** [comment]
đã fix ở bản 1.0.20 mới rồi nha bạn ^^

**Comment by dinhquochan** [comment]
Tuyệt vời 🎉
