### ISSUE TITLE
Lỗi gõ TELEX tiếng Việt ở phiên bản v1.0.20

### ISSUE THREAD

**Issue by dinhquochan** [tuyenvm/OpenKey#53]
Dear,

Minh vua update, hien tai khong the go tieng Viet duoc, khi go xong se bi xoa dau cach va duplicate chu cai, VD, day la go dung telex lien tuc se ra nhu vay:

Lỗỗigox chuwx khoong gox đuocwj nuawx

O doan tren la minh go theo binh thuong nhung no lai bi nhu the mong admin fix loi nay som.

**Comment by tuyenvm** [comment]
Hi, bạn gõ trên phần mềm nào và có đang dùng bộ gõ nào khác không?

**Comment by dinhquochan** [comment]
Hiện tại nó sẽ bị dính chữ hoặc sẽ bị xoá space gần nhất sau đó nhân đôi ký tự có dấu và từ dòng đó trở đi sẽ không gõ tiếng Việt được nữa, khi gõ dòng mới thì lặp lại trường hợp trên.

@tuyenvm mình gửi issue #50, hiện mình chỉ dùng duy nhất OpenKey và trước đó dùng bình thường. Mình vừa Upgrade là bị. Mình phải bật cái Telex của macOS ra để comment issue này cho bạn dễ hình dung.

**Comment by hoangnamitc** [comment]
Thêm lỗi sau:
1. a+w (aư)
2. giĩn (gian~)
3. cacs + banj (cac' ban.)
4. aa (a^)
5. naỳ ( daaú bị sai)

nói chung banr naỳ khas laf nhiều lỗi.

tks!

**Comment by tuyenvm** [comment]
mình thấy lỗi rồi, lỗi khi bật bảng emoji trùng với phím chuyển là bị.
mình sẽ sửa vấn đề này ngay.

**Comment by tuyenvm** [comment]
Các bạn update bản 1.0.20r2 nhé, cảm ơn các bạn. 😅

**Comment by dinhquochan** [comment]
Mình đang trả lời issue này owr phieen barng 1.0.20r2 nhưng có vẻ vẫn chưuảôn, vẫẫncòònmộoosoo looxi :)

**Comment by dinhquochan** [comment]
Coi bộ vẫn lỗi rồi :)

**Comment by tuyenvm** [comment]
Bạn xem lại xem đúng 1.0.20.2 ở thanh tiêu đề bảng điều khiển chưa, mình test nãy giờ vẫn chưa thấy bị

**Comment by dinhtuan1991vt** [comment]
@dinhquochan Mình chạy thử trên 1.0.20.2 ổn nhé. Bạn check lại version hiện tại xem đúng ko.

**Comment by dinhquochan** [comment]
Tốt rồi nha ad.
