### ISSUE TITLE
Không kiểm tra chính tả

### ISSUE THREAD

**Issue by ldkien** [tuyenvm/OpenKey#54]
ko kiểm tra chính tả sau khi nhấn dấu cách khi gõ tiếng anh. ví dụ: rểach (research), ễcute  (execute)

**Comment by causelove94** [comment]
Cái này nó chính là tính năng "Khôi phục phím với từ sai" đó bạn, đã có issue #11 rồi.
Mong bạn @tuyenvm cập nhật tính năng này sớm, mình nghĩ nó quan trọng hơn tính năng gõ tắt (_vì bản thân hệ điều hành cũng đã có tính năng này cho các app hệ thống và 1 vài app khác rồi_) và tính năng tự chuyển chế độ khi đổi ứng dụng.

**Comment by tuyenvm** [comment]
Mình sẽ phát triển tính năng "Khôi  phục phím với từ sai" trước và cập nhật nó trong bản sau.

**Comment by ldkien** [comment]
thank you @tuyenvm

**Comment by tuyenvm** [comment]
Bản 1.1 mới đã có tính năng tự phục hồi phím với từ sai nhé các bạn.

**Comment by causelove94** [comment]
Thật tuyệt vời! Mong chờ phiên bản mới của bạn từng ngày, giờ cũng đã có. Cảm ơn bạn vì tất cả!

**Comment by ldkien** [comment]
thank you các bạn
