### ISSUE TITLE
Lỗi không bỏ dấu w => ư khi không có vần u,o

### ISSUE THREAD

**Issue by khanhvu14** [tuyenvm/OpenKey#55]
<img width="403" alt="Screen Shot 2019-08-07 at 3 08 39 PM" src="https://user-images.githubusercontent.com/4197632/62605912-44c1f080-b925-11e9-9c97-e4500039425a.png">

<img width="570" alt="Screen Shot 2019-08-07 at 3 03 58 PM" src="https://user-images.githubusercontent.com/4197632/62605683-d3823d80-b924-11e9-8c97-46832fbff6ca.png">
Mình gõ w => ư trong khi không có nguyên âm (u,o)

**Comment by tuyenvm** [comment]
hi, có thể bạn đang gõ "/var" rồi chuyển cửa sổ, hoặc click chuột, sau đó bạn quay lại cửa sổ thì OpenKey đã start word mới nên bạn gõ "w" sẽ ra "ư".

**Comment by khanhvu14** [comment]
https://www.youtube.com/watch?v=0hLDauupfbE&feature=youtu.be

**Comment by tuyenvm** [comment]
trong bản mới 1.2 thì lỗi này còn không bạn?

**Comment by khanhvu14** [comment]
Ok rồi bạn nhé

**Comment by khanhvu14** [comment]
mà h có tính năng switch theo apps nên mấy apps này mình để EN nên xài ngon
