### ISSUE TITLE
Lỗi gõ tiếng Việt trên app LibreOffice

### ISSUE THREAD

**Issue by dinhtuan1991vt** [tuyenvm/OpenKey#57]
@tuyenvm Hiện tại e đang xài app LibreOffice để soạn thảo văn bản. Khi sử dụng OpenKey thì gõ bị lỗi (Telex lẫn VNI).
![2019-08-07 18 03 21](https://user-images.githubusercontent.com/5716579/62618395-4e0b8700-b93e-11e9-8415-b03be09616b6.gif)

**Comment by tuyenvm** [comment]
sẽ ngon lành trong bản sau nhé, từ nay sẽ không bị lỗi dạng này nữa ở bản 1.1 kế tiếp :D

**Comment by tuyenvm** [comment]
đã sửa ở bản 1.1 nhé.

**Comment by dinhtuan1991vt** [comment]
Đã test ngon lành cành đào trên ver 1.1 :D
