### ISSUE TITLE
Lỗi nhập tuần -> tùân

### ISSUE THREAD

**Issue by khoalmsendo** [tuyenvm/OpenKey#58]
Khi mình nhập chữ theo thứ tự T U A 6 2 N thì nó sẽ ra Tùân.
Mong bạn kiểm tra và fix lỗi nhé.
Cảm ơn

**Comment by tuyenvm** [comment]
Bạn uncheck mục "Cho phép bỏ dấu tự do" là khắc phục được bạn nhé, tính năng đó hơi vô dụng có lẽ mình sẽ bỏ đi trong bản sau.

**Comment by sydonnguyen** [comment]
Mình vote bỏ chức năng này, không thực tế lắm và đôi lúc gây phiền phức cho người dùng.

**Comment by tuyenvm** [comment]
OK @sydonnguyen  mình sẽ bỏ chức năng này, mình cũng thấy nó khá vô dụng và làm người dùng confuse.

**Comment by khoalmsendo** [comment]
Thanks bạn, đúng là nó làm người dùng confuse thiệt
