### ISSUE TITLE
Cho lựa chọn giữa bỏ dấu kiểu cũ và bỏ dấu kiểu mới

### ISSUE THREAD

**Issue by vangquan** [tuyenvm/OpenKey#6]
Bản thân ứng dụng mặc định của macOS cũng cho phép chuyển đổi giữa hai cách bỏ dấu thanh này. Đề nghị cho lựa chọn giữa bỏ dấu kiểu cũ và bỏ dấu kiểu mới.

Xin xem thông tin tham khảo ở đây https://vi.wikipedia.org/wiki/Quy_tắc_đặt_dấu_thanh_trong_chữ_quốc_ngữ

**Comment by tuyenvm** [comment]
Cảm ơn bạn đã góp ý, mình sẽ thêm lựa chọn này.

**Comment by tuyenvm** [comment]
Cập nhật bản mới 1.0.17 nha bạn, bản mới đã có tính năng này.
