### ISSUE TITLE
Lỗi gõ "đâu" -> "đau6", hiểu -> hieu63 VNI

### ISSUE THREAD

**Issue by ductranit** [tuyenvm/OpenKey#60]
Các ký tự gõ lần lượt là `dau96`, kết quả là `đau6` thay vì `đâu`
Tương tự:
 `hiểu` -> `hieu63` 
`điều` -> `dieu692`

**Comment by tuyenvm** [comment]
Đã fix trong bản 1.1 rồi nha bạn
