### ISSUE TITLE
Không hiển thị bảng điều khiển được

### ISSUE THREAD

**Issue by ductranit** [tuyenvm/OpenKey#61]
Không hiểu sao mình ko vào bảng điều khiển được, nó cứ bị như vầy:
![Screen Shot 2019-08-11 at 10 27 21 AM](https://user-images.githubusercontent.com/2063905/62829198-bb5f3680-bc22-11e9-92cb-13db3c83026f.png)

Mình dùng mac os 10.14.5

**Comment by tuyenvm** [comment]
Hi bạn, bạn thử tải OpenKey bản mới nhất xem

**Comment by ductranit** [comment]
> Hi bạn, bạn thử tải OpenKey bản mới nhất xem

Mình build từ code mới nhất trên `master` đó

**Comment by tuyenvm** [comment]
À, bạn add thêm mấy file vào project là hiện được, tại file project cấu hình thiếu file:
MacroViewController.h
MacroViewController.mm
MyTextField.h
MyTextField.m

**Comment by ductranit** [comment]
à được rồi, thank bạn.
Mà sao lại exclude mấy file đó ra khỏi project vậy?

**Comment by tuyenvm** [comment]
Do `OpenKey.xcodeproj` đó là bản cũ hồi xưa, `OpenKey.xcodeproj` hiện tại có nhiều target test lung tung lắm nên mình không dám commit lên ^^

**Comment by tuyenvm** [comment]
Mà bản source mới tính năng Macro - Gõ tắt chưa ổn định lắm, mình đang sửa lỗi cuối cùng của nó nha bạn

**Comment by ductranit** [comment]
uh, thế mình chỉ build từ tag release cho stable
