### ISSUE TITLE
Lỗi gõ chữ VNI "trỉên" = tri3e6n.

### ISSUE THREAD

**Issue by 1234hdpa** [tuyenvm/OpenKey#62]
Thứ tự bỏ dấu trong các từ triển = trỉên = tri3e6n = tri3en6 hay hỉên = hiển = hi3en6 = hi3e6n không được cập nhật khi có chữ ê hai ô, â, ư, ơ... 
VD: đựơc = d9uo75c, hứơng = hu71o7ng...
Các từ có cụm nhiều nguyên âm ươ, iê, ôi, uô... luôn cần cập nhật dấu lại nếu đã bỏ dấu trước đó.

**Comment by tuyenvm** [comment]
Bạn tạm tắt tính năng "Cho phép bỏ dấu tự do" đi là khắc phục được.
Trong bản update sau mình sẽ bỏ tính năng đó đi, vì rất nhiều bạn confuse.

**Comment by tuyenvm** [comment]
đã cải thiện ở bản 1.1 nhé.
