### ISSUE TITLE
Thêm tính năng tự động viết hoa chữ cái đầu sau dấu chấm

### ISSUE THREAD

**Issue by orekasep** [tuyenvm/OpenKey#64]
Hiện tại khi gõ nhanh một đoạn văn bản, có nhiều lúc mình quên viết hoa chữ cái đầu câu. Nếu Tuyên có thể thêm tuỳ chọn cho tính năng này thì sẽ giúp cho bộ gõ được hoàn thiện hơn.

Cảm ơn Tuyên nhiều.

**Comment by tuyenvm** [comment]
Tính năng này hữu dụng, mình sẽ thêm vào sớm

**Comment by hoangnamitc** [comment]
Nên là một tùy chọn trong ứng dụng (on/off) có những trường hợp không cần viết hoa :)

**Comment by tuyenvm** [comment]
@hoangnamitc okey

**Comment by tuyenvm** [comment]
Đã thêm tính năng này ở bản 1.2 mới nhé.

**Comment by tuyennq1001** [comment]
Hình như tính năng này chỉ hoạt động khi trước đó có 1 dấu Enter phải không @tuyenvm 
Ví dụ như ở đầu ô input thì chữ vẫn đang viết thường 

![image](https://user-images.githubusercontent.com/747698/62998261-2adc5c80-be95-11e9-8e67-be79c69e9832.png)

**Comment by tuyenvm** [comment]
@tuyennq1001 đúng rồi, và sau dấu chấm câu.

**Comment by orekasep** [comment]
Cảm ơn Tuyên nhiều về bản cập nhật mới nhé.
