### ISSUE TITLE
Clear input sau khi xoá 1 từ gõ tắt + Đổi con trỏ chuột sau khi thêm 1 từ gõ tắt + Thêm chức năng sửa 1 từ gõ tắt

### ISSUE THREAD

**Issue by dinhtuan1991vt** [tuyenvm/OpenKey#65]
Hiện tại tính năng gõ tắt đang hoạt động rất tốt. Chỉ có thêm 1 vài feedback nhỏ để improve thêm chức năng này:
- Sau khi xoá 1 từ gõ tắt nào đó nên clear hết 2 input và đưa con trỏ chuột vào input **Từ gõ tắt** để có thể nhập tiếp từ mới.
- Sau khi thêm 1 từ gõ tắt nào đó nên đưa con trỏ chuột vào input **Từ gõ tắt** để có thể nhập tiếp từ mới.
- Có thể sửa trực tiếp từ 1 gõ tắt nào đó thay vì phải xoá rồi thêm mới.

**Comment by tuyenvm** [comment]
ok man, sẽ cải tiến dần dần 👍

**Comment by tuyenvm** [comment]
đã thêm feature của bác ở bản [1.2 RC4](https://github.com/tuyenvm/OpenKey/releases) mới rồi nhé. :D

**Comment by dinhtuan1991vt** [comment]
Chạy quá ngon rồi :D
