### ISSUE TITLE
Tính năng tự động tắt tiếng việt khi ở một ứng dụng cụ thể hoặc một url

### ISSUE THREAD

**Issue by fitz-nguyen** [tuyenvm/OpenKey#66]
Nếu thêm đuợc tính năng này thì hay quá! Có một open source [link](https://github.com/huyphan/NAKL) cũng có tính năng này nhưng mà lâu rồi không đc cập nhật nữa. Cảm ơn nhóm vì phần mềm rất tuyệt.

**Comment by tuyenvm** [comment]
Sẽ cập nhật tính năng này trong bản sau bạn nhé

**Comment by tuyenvm** [comment]
Mình thấy tính năng này chính là tính năng #40 
Mình đang phát triển tính năng này. ;)

**Comment by tuyenvm** [comment]
Cập nhật 1.2 dùng thử nha bạn, dùng tính năng "Chuyển chế độ thông minh" nha bạn.

**Comment by orekasep** [comment]
Tuyên chịu khó đóng các issue đã giải quyết để mọi người cùng tiện theo dõi các tính năng mới nhé.
