### ISSUE TITLE
Lỗi bỏ dấu cuối từ có âm "ưa" khi bỏ dấu cuối "nua7", nuũa, chua7, chuùa  

### ISSUE THREAD

**Issue by vannamhh** [tuyenvm/OpenKey#67]
Lỗi bỏ dấu cuối từ có âm "ưa", gõ u7a thì được, nhưng gõ ua7 thì không được, thêm dấu sẽ thành uùa. như "nua7", nuũa, chua7, chuùa, ruủa,

**Comment by tuyenvm** [comment]
đã sửa lỗi trong bản 1.2 mới nhé

**Comment by vannamhh** [comment]
Thanks
