### ISSUE TITLE
Gõ tắt khi ở bật chế độ tiếng anh chưa sử dụng được

### ISSUE THREAD

**Issue by khanhvu14** [tuyenvm/OpenKey#68]
<img width="1440" alt="Screen Shot 2019-08-13 at 8 40 54 PM" src="https://user-images.githubusercontent.com/4197632/62946372-c2e13400-be0a-11e9-9915-3c5b239468a1.png">

**Comment by tuyenvm** [comment]
cụ thể bạn setup gõ tắt từ gì, gõ ở phần mềm nào vậy @khanhvu14

**Comment by khanhvu14** [comment]
<img width="1440" alt="Screen Shot 2019-08-14 at 8 14 06 AM" src="https://user-images.githubusercontent.com/4197632/62987769-9c9fb080-be6b-11e9-865d-bed28e616851.png">
<img width="1440" alt="Screen Shot 2019-08-14 at 8 14 47 AM" src="https://user-images.githubusercontent.com/4197632/62987774-9f9aa100-be6b-11e9-8e15-3b6a470d9f65.png">
Mình dùng terminal với tiếng anh (switch qua tiếng việt thì ok)

**Comment by tuyenvm** [comment]
sẽ fix luôn và ngay ^^

**Comment by tuyenvm** [comment]
Đã khắc phục ở bản 1.2 RC2 rồi nhé bạn.

**Comment by khanhvu14** [comment]
Cảm ơn nhé :)
