### ISSUE TITLE
Dấu câu bị thiếu hoặc sai vị trí khi gõ tự do

### ISSUE THREAD

**Issue by tranhungdlk** [tuyenvm/OpenKey#7]
Cảm ơn bạn đã thêm lựa chọn bộ gõ cho Mac, mình đang dùng Hackintosh, thấy lâu lắm rồi không có ai phát triển bộ gõ hoàn chỉnh cho Mac.

Bạn có thể khắc phục một số lỗi ở kiểu gõ Telex như này không:

1. Lỗi ở Chữ ƯƠ: nếu gõ Nưoc rồi chữ s để đánh dấu nó sẽ thành Nưóc, Thưòng, Trưỏng.... đại loại là đề xuất bạn chỉnh cho tự thêm móc chữ ơ vào các từ cặp ƯƠ

2. Lỗi ở các chữ có 2 nguyên âm trở lên khi gõ dấu trước ký tự cuối cùng của chữ: Ví dụ lỡ gõ chữ Kiểu mà gõ dấu trước chữ u cuối cùng nó sẽ thành Kỉêu, xảy ra tương tự với chữ Trỉên, thìên, nứơc, tửơng tựơng...

3. Sau khi bỏ dấu xong, lỡ nhấn phím cách (space bar), sau đó xoá dấu cách đi (backspace), nhấn dấu khác thì không đổi dấu được phải xoá cả chữ để gõ lại. Nếu có thể mong bạn thêm phần xử lý cái này nữa. 

Mình đang xài Mojave 14.6
Chúc bạn mạnh khoẻ, duy trì nhiệt huyết phát triển cho cộng đồng xài hệ điều hành Mac công cụ vô cùng quan trọng này!
Trân trọng cảm ơn!

**Comment by tuyenvm** [comment]
Cảm ơn bạn đã sử dụng ứng dụng này.

1. Bạn bật bảng điều khiển, bỏ chọn "Cho phép bỏ dấu tự do" là sẽ chuẩn ngay.
2. Cũng là bỏ chọn "Cho phép bỏ dấu tự do".
3. Mình sẽ thêm tính năng này vô.

Mong ứng dụng sẽ giúp ích được cho cộng đồng macOS và cả Hackintosh.

**Comment by tuyenvm** [comment]
Cập nhật bản mới 1.0.17 nha bạn, bản mới đã có tính năng này.
