### ISSUE TITLE
Dấu bị đổi vị trí khi gõ nhầm

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#70]
Lỡ gõ Sưản (dính chữ n vào), dấu hỏi nhảy qua chữ a, sau đó xóa chữ n thì dấu hỏi không trở lại chỗ cũ là chữ ư, phải xóa hết nguyên chữ "sửa" để gõ lại

Đây là setting của mình:
![image](https://user-images.githubusercontent.com/1819772/62992680-89e2a700-be7e-11e9-9cd5-a2158a0c2ab9.png)

**Comment by tuyenvm** [comment]
Đã fix ở bản 1.2 RC2 rồi nhé, dấu sẽ không bị nhảy nữa 👍

**Comment by reun** [comment]
Lúc mới cài bản 1.2RC2 xong thì nó không bị nhảy dấu nữa. Nhưng xài 1 chút sau thì mình thấy nó bị lại như cũ.
Gõ vẫn ra sưản, nhờ bạn check lại nhé.

**Comment by tuyenvm** [comment]
okey để mình check kỹ lại

**Comment by reun** [comment]
Mình update lên phiên bản 1.23 thì có vẻ sửa được 1 số trường hợp rồi.
Giờ không bị ra sưản nữa.

Nhưng vẫn còn bị:
tuỳa
