### ISSUE TITLE
Thông tin phiên bản

### ISSUE THREAD

**Issue by duongbadu** [tuyenvm/OpenKey#71]
Theo em nên Thêm thông tin về phiên bản, ngày cập nhật trong mục "Giới Thiệu".

**Comment by dinhtuan1991vt** [comment]
@tuyenvm Bác thêm link fanpage vào mục giới thiệu để nhiều người biết tới hơn nhé.

**Comment by tuyenvm** [comment]
Đã có ở bản 1.2 RC2 rồi nhé các bác, bản này khá ổn định rồi.
