### ISSUE TITLE
OpenKey for Windows?

### ISSUE THREAD

**Issue by SakaDream** [tuyenvm/OpenKey#73]
Hiện tại bên Windows đang có Unikey và Gõ Tiếng Việt, nhưng 2 phần mềm này không được cập nhật thường xuyên và hiện tại có khá nhiều lỗi vặt. Mình hi vọng bạn có thể port sang Windows để có nhiều sự lựa chọn hơn

**Comment by tuyenvm** [comment]
Ban đầu mình làm OpenKey tách phần engine và phần vỏ app riêng để dễ dàng cross platform, dự tính bản macOS xong sẽ port qua Windows, nhưng bên Windows có cái EVKey khá bá nên cũng hơi chùn tay 😀, nên chắc mình làm linux trước.

**Comment by tuyenvm** [comment]
Hôm bữa định làm OpenKey Linux trước nhưng dài hơi quá. Thôi thì cái gì dễ làm trước. Nay mới ra OpenKey cho Windows nha bạn.
Xem chi tiết https://github.com/tuyenvm/OpenKey/tree/master/Sources/OpenKey/win32
