### ISSUE TITLE
Lỗi gõ tiếng Việt trên trang https://banhang.shopee.vn/portal/product/category

### ISSUE THREAD

**Issue by ansidev** [tuyenvm/OpenKey#75]
Khi mình nhập tên sản phẩm trên trang https://banhang.shopee.vn/portal/product/category thì bị lỗi gõ tiếng Việt. GoTiengViet không bị.

**Comment by tuyenvm** [comment]
Quay giúp mình clip được không Trí, mình không vào được

**Comment by mrnvdong** [comment]
<img width="452" alt="Ảnh chụp Màn hình 2019-08-15 lúc 10 55 23" src="https://user-images.githubusercontent.com/37010112/63071918-62a5db80-bf4b-11e9-82ba-0d1934a03d57.png">

**Comment by tuyenvm** [comment]
à nãy mình test = Safari không thấy lỗi nên tưởng phải đăng nhập vào trong mới bị, thanks @mrnvdong

**Comment by tuyenvm** [comment]
Tạm thời quick fix bằng cách uncheck tính năng "Sửa lỗi gợi ý trình duyệt" là có thể gõ được nha.

**Comment by tuyenvm** [comment]
Nay test lại trang này thì thấy không còn bị lỗi nữa =]]
