### ISSUE TITLE
thêm phần mềm vào homebrew cask

### ISSUE THREAD

**Issue by nhymxu** [tuyenvm/OpenKey#77]
Mình có tạo 1 PR thêm OpenKey vào homebrew nhằm dễ dàng cài đặt cho người mới.

https://github.com/Homebrew/homebrew-cask/pull/67651

Nếu có thể từ phiên bản sau bạn đặt tên phiên bản và tên file có version giống nhau. Sau này nếu được duyệt thì cập nhật dễ dàng hơn.
Hiện tại
```
https://github.com/tuyenvm/OpenKey/releases/download/v1.2.2/OpenKey1.2RC2.dmg
```

Mong muốn

```
https://github.com/tuyenvm/OpenKey/releases/download/v1.2.2/OpenKey1.2.2.dmg
```
hoặc
```
https://github.com/tuyenvm/OpenKey/releases/download/v1.2.2/OpenKey.dmg
```

**Comment by tuyenvm** [comment]
Tuyệt vời, đồng ý 2 tay 👍

**Comment by nhymxu** [comment]
@tuyenvm mình bị fail CI test vì thiếu appcast
Bạn thêm 1 file releases.atom vào repo hộ mình.
Mẫu tương tự:
https://github.com/fitztrev/shuttle/releases.atom

tài liệu: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md

Lỗi:
```
$ brew cask ci
audit
13.38s==> brew cask audit openkey ✘
==> Downloading https://github.com/tuyenvm/OpenKey/releases/download/v1.2.2/Open
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> Verifying SHA-256 checksum for Cask 'openkey'.
audit for openkey: warning
 - Download uses GitHub releases, please add an appcast. See https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/appcast.md
```

**Comment by tuyenvm** [comment]
Sao rồi bạn, tối qua mình thấy mail nhưng không ngồi máy tính được!

**Comment by nhymxu** [comment]
à mình xử lý xong rồi. Chờ họ review rồi merge thôi

**Comment by nhymxu** [comment]
reviewer báo có version mới nên mình phải update lại.
Sau này khi được vào repo của họ rồi thì bạn có thể chủ động sửa lại file trong repo ( version + sha256 của file dmg ) rồi tạo pull request cho họ là ok

**Comment by nhymxu** [comment]
<img width="632" alt="Screen Shot 2019-08-18 at 16 42 59" src="https://user-images.githubusercontent.com/535617/63222875-59c93a00-c1d7-11e9-85b3-2b1787d524f2.png">
đã được merge rồi nha. Bạn có thể update thêm 1 cách cài vào README

**Comment by vangquan** [comment]
Xin bạn @nhymxu hoặc @tuyenvm  có thể update cask của OpenKey được không? Hiện nay trên Github là 1.2.4 (Build 27) rồi nhưng qua brew thì vẫn 1.2.3 (Build 26). Cảm ơn nhiều.

**Comment by tuyenvm** [comment]
@vangquan mình có tạo pull request rồi, được approved luôn rồi nhưng chưa được merge, chắc phải đợi thêm.

**Comment by tuyenvm** [comment]
@vangquan 1.2.4 mới được merged trên brew rồi nha bạn
