### ISSUE TITLE
Không gõ được dui9 duoi96

### ISSUE THREAD

**Issue by ducmthai** [tuyenvm/OpenKey#79]
macOS 10.14.6 (18G87)
1.2.2 (b 25) nhé bác, VNI không gõ được chữ `đui' toàn ra dui9 trên Skype lẫn Chrome.

Thanks

**Comment by tuyenvm** [comment]
fix liền bác nhé :D

**Comment by ducmthai** [comment]
Không biết phải do design nó thế không nhưng hay gõ tua62n thì nó sẽ là tùâ xong mới tuần :D Đã bật và tắt 'Đặt dấu òa, ùy' mà vẫn không thay đổi :D

**Comment by tuyenvm** [comment]
Do thuật toán bỏ dấu thôi bác ah :D, nó không như Unikey.

**Comment by tuyenvm** [comment]
đã fix ở bản 1.2 RC3 rồi nhé @ducmthai
