### ISSUE TITLE
Lỗi khi gõ ư và ơ

### ISSUE THREAD

**Issue by nxqbao** [tuyenvm/OpenKey#83]
Mình dùng font Palatino trên Word.
Khi gõ ư/ơ bằng phím `]`/`[` thì font chữ bị set về font mặc định.
Khi gõ `uow` hoặc `uwow` thì không có hiện tượng này.

**Comment by tuyenvm** [comment]
Để gõ Palatino trơn tru trên Word, bạn tạm thời tắt tính năng "Sửa lỗi gợi ý trình duyệt" nhé.
Do cơ chế sửa lỗi thanh địa chỉ mà mình chèn thêm ký tự rỗng (có mã Unicode là 0x202F), sau đó mới xóa ký tự rỗng và ký tự bình thường, có thể 0x202F không có trong font Palatino nên Word mới trở về font mặc định.

Mình sẽ tìm ra ký tự rỗng khác và fix trong bản tiếp theo.

**Comment by tuyenvm** [comment]
Đã fix ở bản [1.2 RC4](https://github.com/tuyenvm/OpenKey/releases) rồi nhé :D
