### ISSUE TITLE
Không thể gõ chữ có dấu ngay sau dấu "[" hoặc "{"

### ISSUE THREAD

**Issue by vangquan** [tuyenvm/OpenKey#85]
Phần mềm nghĩ là lỗi chính tả nếu viết tiếng Việt ngay sau dấu "[" hoặc "{".
Ví dụ: muốn gõ "[Tổng số" thì sẽ được kết quả là "[Toorng số". Vấn đề tương tự với dấu "{".
Nếu tắt tính năng _Kiểm tra chính tả_ thì không gặp vấn đề nữa.
_
macOS 10.14.6; OpenKey 1.2.4 (Build 27)

**Comment by tuyenvm** [comment]
đã fix ở bản [1.2 RC5](https://github.com/tuyenvm/OpenKey/releases). brew cũng đã được merge :D
