### ISSUE TITLE
Không thể gõ được chữ "quởn" (rảnh rỗi)

### ISSUE THREAD

**Issue by minhbrvn** [tuyenvm/OpenKey#86]
Khi gõ chữ "quởn" thì tự động thêm dấu vào thành chữ "qưởn".
Từ này có nghĩa là "rảnh rỗi" trong tiếng địa phương miền Tây Nam Bộ. Chi tiết:
https://vi.wiktionary.org/wiki/qu%E1%BB%9Fn#Ti%E1%BA%BFng_Vi%E1%BB%87t

**Comment by tuyenvm** [comment]
Đã fix ở bản [1.2 RC5](https://github.com/tuyenvm/OpenKey/releases).
Brew cũng đã được merge :D
