### ISSUE TITLE
Không gõ được tiếng Việt sau khi Macbook wake up từ sleep

### ISSUE THREAD

**Issue by ducmthai** [tuyenvm/OpenKey#87]
Bị lần này là lần thứ 2 bác nhé, phải restart máy :( 
<img width="1620" alt="typing" src="https://user-images.githubusercontent.com/13193688/63700723-1b400a80-c7e9-11e9-8494-09c5524113dd.png">

**Comment by tuyenvm** [comment]
Lần sau nếu bị bác thử tắt OpenKey đi rồi bật lại thử.
Mình sẽ cố gắng trace ra lỗi này.

**Comment by tuyenvm** [comment]
Chà, có bạn thì chỉ cần tắt đi bật lại là được.
Mình không lưu log bác ak.
Chắc hay bị trên macbook hơn, để mình trace trên macbook :D

**Comment by lilws** [comment]
mình xác nhận cũng bị lỗi này, app bị đơ hoàn toàn, phải tắt app mở lại thì mới gõ được.

**Comment by tuyenvm** [comment]
Đã tìm ra giải pháp :D, mình sẽ fix ở bản sau nhé.

**Comment by tuyenvm** [comment]
Hi all, mình mới thử fix bằng cách stop OpenKey khi sleep máy, và bật lại OpenKey khi Awake, các bạn cập nhật phiên bản 1.4 nhé.

**Comment by congvmit** [comment]
Hi @tuyenvm, 
Mình xin lỗi mn vì tiếp tục report lỗi ở closed issues này.
Mình đang gặp vấn đề tương tự "Không gõ đc tiếng Việt sau khi wakeup từ sleep" trên MacOS Monterey với OpenKey ver2.0.5

Mình đã tắt và bật lại OpenKey, nhưng vẫn k thể gõ đc tiếng Việt. 
Mong mn hỗ trợ mình nhé.

**Comment by congdanh1608** [comment]
Gio72 bi5 lai5 nua7 roi72

**Comment by hieptuanle** [comment]
Máy em/mình cũng mới bị lỗi này gần đây. Có thử tải phần mềm gõ tiếng Việt khác thì cũng bị luôn ạ.

Phiên bản OpenKey: 2.0.5 (build 49) 
Mac M3 OS Version 15.1.1 (24B91)

**Comment by congdanh1608** [comment]
Mới phát hiện ra là do app Chrome Remote desktop. Cứ bật nó lên là máy hết gõ được tiếng việt.
