### ISSUE TITLE
Thừa kí tự khi gõ dấu trên trình duyệt

### ISSUE THREAD

**Issue by nxqbao** [tuyenvm/OpenKey#88]
Gõ chuỗi bắt đầu bằng `đ`, `ă` và `â` trên trình duyệt sẽ bị đổi thành `dđ`, `aă` và `aâ`.

![image](https://user-images.githubusercontent.com/17340327/63830750-1caf3580-c997-11e9-9b00-1470d72c3bd0.png)

![image](https://user-images.githubusercontent.com/17340327/63830802-45372f80-c997-11e9-83c1-7894452641aa.png)

**Comment by tuyenvm** [comment]
Lỗi này là lỗi autocorrect trên các trình duyệt chromium đó bạn, chưa có bộ gõ nào fix được hoàn toàn, hiện mình có cách khắc phục rồi nhưng có thể cho trải nghiệm gõ tiếng Việt kém nên mình vẫn chưa áp dụng, xem #37 nhé.
Hiện mình vẫn đang tìm cách tốt nhất để khắc phục.
