### ISSUE TITLE
icon màu trắng cho darkmode

### ISSUE THREAD

**Issue by tuzebra** [tuyenvm/OpenKey#9]
Nên chuyển icon trên status bar thành màu trắng khi người dùng đang sử dụng darkmode, như thế sẽ ton sur ton với các icon của các ứng dụng khác.

**Comment by lamhieu-vk** [comment]
@tuyenvm nếu có thể, rất mong bạn sẽ sử dụng màu đơn sắc cho icon ở thanh nav như những ứng dụng khác nó sẽ đồng bộ giao diện hơn, cảm ơn bạn rất nhiều.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/9839768/62098606-418b8c80-b2b5-11e9-8fee-3682a5a5efb3.png">

**Comment by tuyenvm** [comment]
Cảm ơn bạn, mình sẽ thêm tuỳ chọn cho icon, do mình thích màu mè nên mới thiết kế màu đỏ :D

**Comment by lamhieu-vk** [comment]
cảm ơn bạn, taị mình không biết c nên không pr được, hi vọng bạn cập nhật sớm để mình cập nhật ứng dụng lại.

**Comment by dieupxse** [comment]
vote cho việc chuyển icon về đơn sắc cho đồng bộ với các icon hệ thống :D

**Comment by tuyenvm** [comment]
update bản mới 1.0.17 nha các bạn
