### ISSUE TITLE
Không phát ra âm thanh khi chương trình tự động chuyển giữa tiếng Anh và tiếng Việt

### ISSUE THREAD

**Issue by ansidev** [tuyenvm/OpenKey#90]

**Comment by tuyenvm** [comment]
Có mục "Kêu beep" trong bảng điều khiển đó Trí, tick vào đó là ok.

**Comment by ansidev** [comment]
@tuyenvm Ý là mình muốn vẫn chọn kêu beep, nhưng mà chỉ kêu khi mình chuyển thủ công, còn chuyển tự động thì không kêu.

**Comment by tuyenvm** [comment]
À ok, hợp lý, mình sẽ update trong bản sau 👍

**Comment by tuyenvm** [comment]
Đã update trong bản 1.4.1 nhé ^^
