### ISSUE TITLE
Thêm tùy chọn không hiện popup khi chuyển mã thành công

### ISSUE THREAD

**Issue by ansidev** [tuyenvm/OpenKey#91]

**Comment by tuyenvm** [comment]
Tắt tính năng "Thông báo khi chuyển xong" trong bảng Công cụ chuyển mã là ok.

**Comment by ansidev** [comment]
Có vẻ đây là issue, hiện tại mình không hề set hotkey cho tính năng chuyển mã nhanh, nhưng tự nhiên cái popup lại hiện ra.

**Comment by tuyenvm** [comment]
Có phải mới chạy OpenKey, bấm phím fn là nó hiện không nhỉ, mình mới tìm ra!

**Comment by ansidev** [comment]
Hiện tại, mình chưa xác định được cách reproduce.

**Comment by cosmospham** [comment]
Mình xác nhận là chỗ hộp thoại chuyển mã có vấn đề. Mình không cài hot key, cũng không thao tác gì liên quan chuyển mã. Đang làm bình thường thì hộp thoại báo chuyển mã thành công hiện ra vậy thôi.

**Comment by tuyenvm** [comment]
Các bạn update bản 1.4.1 để khắc phục hoàn toàn nhé.
