### ISSUE TITLE
[v1.4] Lỗi xung đột chuyển mã với chức năng Screenshot của Mac

### ISSUE THREAD

**Issue by letinhminh** [tuyenvm/OpenKey#92]
Mình vừa cập nhật lên phiên bản 1.4 build 31 sáng nay thì thấy bị lỗi này. Mình thường sử dụng chức năng screenshot và lưu vào clipboard mặc định của mac (command + control + shift + 4), sau đó paste vào ô tin nhắn hoặc các tài liệu này nọ.

Tuy nhiên, trong phiên bản mới cập nhật, ngay khi vừa screenshot xong, lập tức Open Key mở ra 1 hộp thoại "Không có dữ liệu trong clipboard".

Tình trạng này chỉ bị với tính năng screenshot này thôi. Còn 3 kiểu screenshot còn lại (cmd+ctr+3, cmd+ctr+shift+3, cmd+ctr+4) thì không bị ảnh hưởng.

Lỗi này về cơ bản không ảnh hưởng gì đến chức năng và hoạt động bình thường. Chỉ hơi khó chịu trong trải nghiệm khi hộp thoại này liên tục nhảy ra.

**Comment by tuyenvm** [comment]
Cảm ơn bạn đã báo bug, mình sẽ sửa luôn và update ngay.

**Comment by tuyenvm** [comment]
Update bản 1.4.1 để khắc phục hoàn toàn bạn nhé.
