### ISSUE TITLE
Bất tiện khi gõ nhiều địa chỉ mail có sẵn gợi ý trong ứng dụng Mail mặc định.

### ISSUE THREAD

**Issue by drnhat** [tuyenvm/OpenKey#93]
Khi soạn mail cho nhiều người (đã có sẵn gợi ý) thì cần gõ thêm phím mũi tên mới có thể làm được, không thì khi nhập địa chỉ thứ 2 sẽ xoá luôn địa chỉ mail đã nhập.

**Comment by tuyenvm** [comment]
Có thể đây là do tính năng tự phục hồi phím với từ sai đó bạn, nếu tạm tắt nó đi thì sẽ không bị.
Mình sẽ thêm tính năng tạm tắt check chính tả trong bản sau.
