### ISSUE TITLE
Lỗi khi gõ trong iterm2

### ISSUE THREAD

**Issue by ducdev** [tuyenvm/OpenKey#95]
Hi, bạn xem thử GIF này nhé

http://g.recordit.co/ehQrCiuPIJ.gif

**Comment by tuyenvm** [comment]
Bạn thử tắt tính năng sửa lỗi địa chỉ trình duyệt.
Mình đoán do iterm không nhận ký tự rỗng nên chữ sẽ bị xoá lố thêm 1 ký tự nữa.

**Comment by ducdev** [comment]
![image](https://user-images.githubusercontent.com/3524016/64584432-d3131180-d3be-11e9-8b6e-1d6e3be40876.png)
Hi cho mình hỏi tính năng đó ở đâu ?

**Comment by tuyenvm** [comment]
À, bạn đang xài bản cũ rồi, bạn update lên bản 1.4.1 mới nhất nhé, sẽ có thêm nhiều tính năng hay.
Có thể lỗi đó cũng đã được fix rồi luôn :D

**Comment by ducdev** [comment]
OK, ngon rồi, cảm ơn bạn, keep rocking!

**Comment by tuyenvm** [comment]
Thanks bạn ^^, có tính năng “chuyển chế độ thông minh” là tính năng do cộng đồng yêu cầu đó bạn, mình thấy nó rất hữu ích với dev. Bạn dùng thử nhé.

**Comment by ducdev** [comment]
Hi bạn, tính năng này nay quá, AE team mình rất thích, sẽ follow OpenKey và sử dụng lâu dài.
