### ISSUE TITLE
Kích hoạt gõ tắt bằng chấm phẩy

### ISSUE THREAD

**Issue by reun** [tuyenvm/OpenKey#96]
Hiện tại mình có 1 bảng gõ tắt, tuy nhiên trong trường hợp gõ chuỗi tắt xong gõ chấm/phẩy thì không hiện ra nguyên chữ, mà mình phải bấm space rồi quay lại gõ dấu, hơi bất tiện.

**Comment by tuyenvm** [comment]
Mình sẽ thêm các dấu ngắt câu để kích hoạt gõ tắt trong bản sau nhé ^^

**Comment by tuyenvm** [comment]
Đã thêm dấu ngắt câu để dùng gõ tắt ở bản 1.5

**Comment by reun** [comment]
Mình đã xài được ngon lành. Cảm ơn bạn nhiều.
